### ISSUE TITLE
Issue with crashes in Forages with some settings for fraction consumable

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8332] opened 2023-10-05 01:50 UTC
### What happened?

[Fails.zip](https://github.com/APSIMInitiative/ApsimX/files/12811440/Fails.zip)

Example attached. In Forages for SurfaceOrganicMatter, if live fraction consumable is <> 0 and dead fraction <> 0 then it crashes.

Workaround is to set the live fraction to 0

### What Operating System are you on?

Windows

**Comment by par456** [comment] 2023-10-09 23:16
Just having a look at this, there are a few things. The met file you provided is missing it's headers and is not reading in correctly, it's name also doesn't match the weather files that the simulations are looking for. The met file reader was also having trouble reading the dates in the file, so I've written a quick patch for that.

After fixing that, I got  the error: Removal of DM resulted in loss of mass balance

This was being caused by the operation: 2021-02-15 [SimpleGrazing].GrazeToResidual(1800) 
Which is the first operation in the file that runs when the simulation runs.

Is that the same error you were having?

**Comment by par456** [comment] 2023-11-14 01:55
Is this problem still occurring? If so I'll need some more information to replicate your problem. If not, I'll close this issue and the other one that's related to it.

**Comment by sno036** [comment] 2023-11-15 21:52
Still an issue - trying to sort a good (bad) example

@rcichota

**Comment by rcichota** [comment] 2023-11-15 22:10
Here is the simulations that shows the mass balance error:
[Simulation (with simpleGrazing - Fails).zip](https://github.com/APSIMInitiative/ApsimX/files/13370091/Simulation.with.simpleGrazing.-.Fails.zip)

**Comment by par456** [comment] 2023-11-16 00:14
For Dean when he comes to look at this:

The report is trying to call [AgPRyegrass].Harvestable.Digestibility, which requires the DigestibilityTotal from PastureAboveGroundOrgan to be calculated. However, for some reason that organ is not initialised until after the report has already run, leading to it trying to Sum() a null value.

Tracing this back to PastureSpecies, the organ is initialised in the OnSimulationCommencing function which is attached to the "Commencing" event. Clearly there is some sort of ordering bug here, since Commencing should be happening well before the report.

**Closed** 2023-11-21 03:49 UTC
Labels: bug, interface/infrastructure, Livestock and forages
