### ISSUE TITLE
Tweaks to performance test site

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#3553] opened 2019-02-25 17:32 UTC
The following relate to the results shown when clicking the Tabulated or Graphical results buttons highlighted below

![image](https://user-images.githubusercontent.com/7295858/53355740-9174c900-398e-11e9-9737-3a04b27670d5.png)

1.  The Tabulated Results on the performance test site show a red cross if results are worse by a specified threshold and show a green tick if they have improved by any amount.  The green ticks should only be applied if the results have improved by more than the threshold values as well otherwise it gives the false impression that changes are doing more good then they are.
![image](https://user-images.githubusercontent.com/7295858/53356832-2a0c4880-3991-11e9-9155-9d5ba0d974c4.png)

2.  The colors on Graphical results currently show as:
      Black for accepted results that were considered poor (blow a certain threshold)
      Orange for current results that are still poor
      Grey for accepted results that were considered good (above a certain threshold)
      Green for current results that have stayed the same or improved
      Red for current results that have got worse beyond a specific threshold
These are all fine but we need to add another color so the green bars can be separated into results that have stayed the same (suggesting white) and results that have improved (keep green) so that we can get a clearer impression of the extent of improvement.
![image](https://user-images.githubusercontent.com/7295858/53356761-0517d580-3991-11e9-9276-929be78ca94c.png)

3  The graphs are way to big, could be shrunken considerably so we can see lots more on a page.  It is mostly the colors that we need to get a quick look at.  Individual graphs don't need x and y axis labels but a name identifying the variable is still needed somewhere.  A tool tip showing the value behind the bar would also be helpful

**Comment by jbrider** [comment] 2019-02-25 21:54
I'm glad I read this one before commenting on the previous one... the description you gave above would be good to have available somewhere for people who haven't seen this page before.  
Similarly, if you removed the labels it would be good to have an example somewhere on the page that showed a definition of the different columns. 
Are those thresholds able to be viewed somewhere? 
Can you view the actual values somewhere?

**Comment by HamishBrownPFR** [comment] 2019-02-26 00:38
Good suggestion to include descriptions on what the colors mean for the graphs.  There is something at the bottom of the tables but it should be at the top. Descriptions of the thresholds should be there some where too.

**Comment by HamishBrownPFR** [comment] 2019-02-26 18:11
Can I also add a tweek to the Obs vs Predicted graphs to this issue.  The tool tip shows up the x and y coordinates of a point when you hover the mouse over it.  It would be enormously helpful if the tool tip also showed the simulation name so we could identify which simulations have gone errant.  

![image](https://user-images.githubusercontent.com/7295858/53435814-8b4e1d80-3a5e-11e9-8e6e-6e198ef48f06.png)

**Comment by hol430** [comment] 2019-02-27 00:18
> The graphs are way to big

They seem ok to me - is [this](https://apsim.csiro.au/APSIM.PerformanceTests/TestsCharts.aspx?PULLREQUEST=3539) the page you're talking about? I can see lots of graphs at once:

![image](https://user-images.githubusercontent.com/36427516/53456136-decd6500-3a78-11e9-959b-a1bd6ce33ba2.png)

**Comment by HamishBrownPFR** [comment] 2019-02-27 01:59
Yes that is the page.  The idea of these graphs is really to give an overall impression of the amount of green relative to the amount of red and show which crops and variables it is coming from.  Ideally we would be able to see all the graphs for a crop on a single page.  A heat map showing up intensity and location of changes would probably be the best way to achieve that but that would be more work so a quick fix would just be to squeeze more graphs into the page.  We don't need to see exact comparisons for each variable as a click of each graph links to the detailed xy comparison graphs.

**Comment by hol430** [comment] 2019-02-28 02:26
@HamishBrownPFR do we want both the heat map and the bar charts? Here's what it currently looks like:

![image](https://user-images.githubusercontent.com/36427516/53536865-a9497a00-3b53-11e9-97cd-e48c4dd8aaf0.png)

Clicking on a particular cell in the heat map will take you to the detailed xy comparison graphs for that variable (well, for the table containing that variable actually). I don't see any disadvantage to having both, other than perhaps a *slightly* longer page load time.

**Comment by HamishBrownPFR** [comment] 2019-02-28 03:16
Wow, I thought it might take longer to make a heat map, that's pretty cool.  Would it be possible to have three separate heat maps, one for NSE, one for R2 and one for RSE and break them into sections so it is quick to identify the test sets (maize, wheat etc).  Also is it possible to get some intensity on the colors to show the extent of change relative to the accepted stats.

I don't see any problem in keeping both the heat map and bar charts.

**Comment by jbrider** [comment] 2019-02-28 21:34
Agree with Hamish - the heatmap looks great.
Would it be easy to add some filter functionality to the outputs?
Just being able to turn off the unchanged entries in the table output would be useful.

**Comment by hol430** [comment] 2019-02-28 22:50
Is this what you had in mind Hamish? I haven't looked into colour intensity just yet, but I will. It's worth noting that I can't see all of the results on one screen when displaying the data this way.

![image](https://user-images.githubusercontent.com/36427516/53602312-1b749a00-3bfa-11e9-8705-40f452b0f0e9.png)

Jason - I haven't looked into it yet but that should be simple enough.

**Comment by HamishBrownPFR** [comment] 2019-02-28 23:53
@hol430 yes, that is brilliant.  Do the pixles still link to their corresponding Obs vs Pred graph?  If you are able to get colour intensities working that page will be extremely powerful.   We probably need to review the meaning and use of the orange colour on these graphs also.

**Comment by hol430** [comment] 2019-03-01 02:37
@jbrider In the tabulated results view, I've added a checkbox to only show changed results. Would you prefer this checked or unchecked by default?

**Comment by jbrider** [comment] 2019-03-01 04:16
I'd go with checked - pretty sure that most of the time that's what we're interested in.
Don't think it really matters though.

**Comment by hol430** [comment] 2019-03-04 00:29
@HamishBrownPFR here is what I've come up with. Basically, greyscale is for unchanged results. Black = bad, through to white = good. Green is for improved results, darker = smaller improvements, brighter = larger improvements. Red is for results which have worsened, darker = smaller changes, brighter = larger changes.

I've removed the RMSE heatmaps for now, as I couldn't thinks of a good way to generate a colour for RMSE - what constitutes a universally 'good' or 'bad' value for RMSE? My evaluation of the other stats like rsr/nse is also somewhat arbitrary but at least it provides a decent spectrum of colours. The actual threshold values will be available on the help page. Basically, if NSE is less than -10 or RSR is greater than 10, it shows up as pure black. Don't know if these values are good or not, but I've set it up so that they're really easy to change.

Any thoughts?

![image](https://user-images.githubusercontent.com/36427516/53703204-ef0b8880-3e5a-11e9-8eae-5bdab336be64.png)

**Comment by HamishBrownPFR** [comment] 2019-03-04 01:35
@HamishBrownPFR that looks really good.  It is not possible to put a threshold on RMSE because it is an absolute value.  RSR is RMSE normalised to observed standard deviation to make it relative and as we have that in there it will be OK to exclude RMSE.  Absolute values of RMSE are given in the table view if people want to see them.  An NSE < 0 and an RSR > 1 mean there is essentially no agreement between the model and observations so perhaps these are more suitable to set at limits to the grey scale.  
If Dark = good and light = bad it makes sense if larger improvements are light green (more good = light still) but should you invert the red so that large changes in the bad dirrection are darker and smaller changes in the bad dirrection are lighter.

**Comment by hol430** [comment] 2019-03-04 02:36
Those are good suggestions - which I've now implemented. I'm pretty sure I implemented all of the changes mentioned in this thread, but if you notice any missing, let me know. 

The changes won't go live on the website until I publish them, which I won't do until the pull request gets merged.

**Comment by HamishBrownPFR** [comment] 2019-03-04 03:17
@hol430 Do the pixles link through their corresponding obs vs pred graph and is there a tool tip when you hover a pixel to tell you what variable it is?

**Comment by hol430** [comment] 2019-03-04 05:25
Yep there's a tooltip when you move the mouse over a pixel which tells you which variable you're looking at. When you click on the pixel, it takes you to the same page which you get when you click on one of the bar charts. Is this the page you're talking about? I was going to include a screenshot of the page I mean, but #3552 seems to be rearing its ugly head again.

**Comment by HamishBrownPFR** [comment] 2019-03-04 17:52
@hol430 thats great.  Thanks for your work on this.  The reference panel are going to be getting more involved in commenting on and reviewing pull requests so it is good to have a nice dashboard to the performance tests.

I have seen #3552  occurring again also

**Comment by jbrider** [comment] 2019-03-04 21:25
@hol430 Nice work - that does look good.

**Closed** 2019-03-07 04:07 UTC
Labels: jenkins, newfeature

**Comment by hol430** [comment] 2019-03-07 04:39
The changes I've implemented are now live. How bad is the "graphical results" page load time for you guys? It's kind of bad for me, but so are the other pages on the website - ie I'm not sure if the delay is caused by the heatmap or not. 

Also Hamish FYI:
> The green ticks should only be applied if the results have improved by more than the threshold values as well otherwise it gives the false impression that changes are doing more good then they are.

I've made this change, but it will have no effect on existing data - it will only affect data generated after the change went live.

**Comment by hol353** [comment] 2019-03-07 04:54
When I click on a heat map pixel it times out. The loading of the graphical results page is pretty good for me.

**Comment by hol430** [comment] 2019-03-07 04:56
Yep, clicking on a heatmap pixel is equivalent to clicking on one of the bar graph series. It will time out for now, until we fix the database issues.

**Comment by HamishBrownPFR** [comment] 2019-03-07 18:44
It took about 15 seconds to load fully but because it loads dynamically it is quite entertaining to watch.

**Comment by jbrider** [comment] 2019-03-07 21:39
Yeah, it's a bit steady - if it was just a progress indicator it would probably seem longer, but the loading charts are ok.

**Comment by hol430** [comment] 2019-03-07 21:57
Yeah I'll see what I can do, but it will have to wait until I fix #3552 and possibly one or two other things which I'm working on at the moment.
