### ISSUE TITLE
Add error bars in graphs

### ISSUE THREAD

**Issue by wolfgang-boku** [APSIMInitiative/ApsimX#1097] opened 2016-08-30 12:12 UTC
Currently there is no option to display error bars in the graphs. However, when comparing observed and simulated values, it would be very valuable to have error bars as well to judge deviations.

**Comment by zur003** [comment] 2016-08-30 12:44
This is a duplicate of #669.

**Closed** 2017-11-20 02:31 UTC

**Comment by hol353** [comment] 2017-11-20 05:52
@HamishBrownPFR - FYI

Forgot to mention that you need to put "Error" on the end of the column name in the observed file e.g.

If you have Wheat.AboveGround.Wt, you will need a column called Wheat.AboveGround.WtError
