### ISSUE TITLE
errors in the address of file when using the released APSIMX vesion

### ISSUE THREAD

**Issue by junqi108** [APSIMInitiative/ApsimX#2371] opened 2018-03-04 23:35 UTC
the address of file going wrong when using the released APSIMX version for those models in the prototype folder. see the photo below.
![image](https://user-images.githubusercontent.com/13222562/36952166-04220f2c-2071-11e8-8b77-ba60c818f067.png)
selecting the data again and run it can make it works.

**Comment by hol430** [comment] 2018-03-05 04:45
Same as #1783

**Comment by zur003** [comment] 2018-03-08 01:10
@hol353 - I've issued a pull request on APSIM.Shared that creates relative paths, but doesn't insert the %root% macro. With this, Weather file paths (and a few other paths) will be stored relative to the folder holding the simulation, rather than relative to the APSIM executables. This won't fix the problem in the short term, but it should in the long term, as new .apsimx simulations will be saved with relative paths that don't use %root%. I leave it to you to decide whether this is what we want.

**Comment by hol353** [comment] 2018-03-08 22:31
The reason why %root was invented was so that the user could open an example, save it to their "MyDocuments" or somewhere and it would work. If the weather file name is relative to where the .apsimx file is located this won't work.

**Comment by zur003** [comment] 2018-03-08 23:55
Ah, of course. Well, that means my recent change in APSIM.Shared was not the right thing to do, and should be reverted. Perhaps we need to treat stuff in the Examples folder as a special case? That is, should we apply the %root% macro only to paths under %root%\Examples, rather than to everything under %root%?

**Comment by hol353** [comment] 2018-03-09 00:37
Well I've seen developers copy files  out of the tests or prototypes directory as well.

**Comment by zur003** [comment] 2018-03-09 01:14
Suppose, like Junqi, we're a developer running an installed release, but want to run a simulation from the prototypes directory (available to developers only). If we use the %root% macro and try to open it, the weather file won't be found, since the "root" has changed. In contrast, if we don't don't use the %root% macro, the weather will be found when we first open the simulation, but if we save the simulation somewhere else, the weather won't be found. 

I think the latter problem is actually more general - if I open any simulation not in the Apsim folder hierarchy, then save it somewhere else, all the relative paths within it will be broken unless we work through the whole simulation, look for relative paths, and either change the paths, or copy the files they're pointing to.

**Comment by rcichota** [comment] 2018-03-13 04:04
I came across this error trying to run a simulation with plantain. I got the file from the Prototypes folder and saved somewhere else, the links to files were broken as Junqi reported (this happened for met files as well as Observed data). The problem is, one cannot simply change the path in the UI, it crashes. the only solution I found was to open the simulation in an editor and then put the right path. This may be caused by Eric's latest change? 

In case it is useful, I chased the error that made the sim crash, it happens on the GetAbsolutePath method. The original Plantain simulation has this address on the Weather node:
   <FileName>Ruakura.met</FileName>
which results in GetAbsolutePath outputing:
   "C:\\ApsimX\\Prototypes\\Plantain\\Ruakura.met"
After I save the simulation somewhere else, without any other modification, GetAbsolutePath outputs
   "\\\\Lin-file\\home$\\HRARXC\\My Documents\\RCichota\\Projects\\FRNL\\ForageSpecies\\DiversePastures\\Ruakura.met"
Which causes an error:
   'Cannot find weather file 'Lincoln-Broadfields.met'
If I browse for the location of the weather file, the either UI crashes or give another error (I wasn't able to tell when one or the other occur):
  'The given path's format is not supported.'
This is what is written under the Weather node in the .apsimx file: 
   <FileName>file:\\\C:\Apsim_dev\Data\MetFiles\Other\Ruakura.met</FileName>
Which is interpreted by GetAbsolutePath as: 
   "\\\\Lin-file\\home$\\HRARXC\\My Documents\\RCichota\\Projects\\FRNL\\ForageSpecies\\DiversePastures\\file:\\\\\\C:\\Apsim_dev\\Data\\MetFiles\\Other\\Ruakura.met"
I had to manually change the path in a text editor to actually work:
   <FileName>C:\Apsim_dev\Data\MetFiles\Other\Ruakura.met</FileName>
"C:\\Apsim_dev\\Data\\MetFiles\\Other\\Ruakura.met"

**Comment by zur003** [comment] 2018-03-13 22:28
@hol353 - I've submitted a pull request for APSIM.Shared that reverts to the old code. Please merge it.

**Comment by HamishBrownPFR** [comment] 2018-03-23 00:27
Was this issue resolved?

**Comment by zur003** [comment] 2018-03-23 00:53
No, not really. My attempted cure was worse than the disease.

I think that perhaps what we really need is some logic in the "Save As" operation that fixes up any relative paths to external files. Unless someone has a better idea...

**Comment by hol430** [comment] 2019-10-18 02:51
@hol353 @zur003: Is there a reason why we can't just save the path to the met file as an absolute path?

**Comment by hol353** [comment] 2019-10-18 03:01
**Use case 1**: Person A gives a .apsimx file to Person B. The .apsimx points to a met file in the Examples\WeatherFiles directory. If the GUI stores an absolute path then this won't work.

**Use case 2**: User opens an example in the GUI. If the path in the example .apsimx file has an absolute path (to C:\Program Files\APSIMxxxx.xx.xx\Examples\WeatherFiles) then this will be different depending on the release the user is using.

1. We need the GUI to try and store the path to weather, EXCEL, input files etc as relative to the .apsimx file.
2. If it can't do 1 then it should use %root% which refers to the parent directory of the 'bin'.
3. If it can't do 1 or 2 then it uses an absolute path.

**Comment by hol430** [comment] 2019-10-18 05:09
What if the GUI always stores file paths as relative to the .apsimx file. We then edit the example files in a text editor and store an absolute path. This would cover both of your use cases.

I just think we should do away with %root% in favour of something simpler as I regularly see apsim get confused about the path to a met file. Can't remember the exact sequence of actions but often when I change the .met file path in the GUI, it will store something like C:\ApsimX\Bin\lincoln.met.

**Comment by hol353** [comment] 2019-10-20 19:30
How do you represent a relative path when the met file is on a different drive?

**Comment by hol430** [comment] 2020-05-15 02:06
@hol353 we should add a use case 3 to your above comment, which was highlighted by Eric earlier in this thread:

> Suppose, like Junqi, we're a developer running an installed release, but want to run a simulation from the prototypes directory (available to developers only). If we use the %root% macro and try to open it, the weather file won't be found, since the "root" has changed. In contrast, if we don't don't use the %root% macro, the weather will be found when we first open the simulation, but if we save the simulation somewhere else, the weather won't be found.

I believe this is mutually exclusive with your use case 1. Use case 3 demands that we not use %root%. Use case 1 demands that we do use %root%. We could perhaps only use %root% for files under the Examples directory, but this seems a bit janky. Otherwise, we might have to choose which of these use cases we actually want to support.

**Comment by hol353** [comment] 2020-05-15 02:33
> If we use the %root% macro and try to open it, the weather file won't be found, since the "root" has changed

Why not?

> In contrast, if we don't don't use the %root% macro, the weather will be found when we first open the simulation, but if we save the simulation somewhere else, the weather won't be found.

I don't understand this either. Need to be a bit more precise with the wording.

**Comment by hol430** [comment] 2020-05-15 02:37
Let's say I'm running the released version, but I have also cloned apsim on my computer, so that I can access the prototypes. Let's say I use the released version and open up the weirdo prototype. The met file will be pointing to %root%\Prototypes\WEIRDO\lincoln.met. %root% will be resolved to "C:\Program Files\Apsimxxxx.xx.xx.xx\". However, the Prototypes directory is not shipped with the installed version, so apsim will not be able to find the met file at %root%\Prototypes\WEIRDO\lincoln.met.

**Comment by hol353** [comment] 2020-05-15 02:41
Ahh ok. How about getting rid of %root% and store all paths as relative to the .apsimx file. If it is on another drive then use an absolute path.

**Comment by hol430** [comment] 2020-05-15 02:49
From your comment earlier in this thread:

> The reason why %root was invented was so that the user could open an example, save it to their "MyDocuments" or somewhere and it would work. If the weather file name is relative to where the .apsimx file is located this won't work.

This is basically your use case 2. Getting rid of %root% would break this. As I said, I think these use cases may be mutually exclusive and we may have to choose which ones we want to support.

**Comment by hol353** [comment] 2020-05-17 21:44
> 
    We need the GUI to try and store the path to weather, EXCEL, input files etc as relative to the .apsimx file.
    If it can't do 1 then it should use %root% which refers to the parent directory of the 'bin'.
    If it can't do 1 or 2 then it uses an absolute path.


I can't see any better way to store paths than this. We're never going to get the perfect solution it seems. I would suggest we wrap the code that deals with this in a set of methods somewhere that we unit test. e.g.
`void ToAbsolute(string apsimPath);`
`void ToApsimPath(string absolutePath);`

where _ApsimPath_ is the path written to the .apsimx file. All models that want to store a path in the .apsimx file must call these methods.

**Comment by hol430** [comment] 2020-05-17 22:27
Agreed about needing some decent tests for this once we make our minds up. However, that three step algorithm you mentioned doesn't necessarily cover all use cases. E.g. the wheat example would be storing its met file path as a relative path, meaning when the user opens it and saves it to somewhere else, it will fail due to using a relative path.

In that algorithm , we would only use %root% if the met file is on another drive (or retrieving a relative path failed for some other reason we haven't thought of).

I think the simplest solution would be to never use %root% when converting to a relative path (but retain functionality for resolving %root% when converting a relative path to an absolute one). Then just manually change the example files to all have %root%. From then on, whenever we change the file path in the gui, just use relative if possible otherwise use absolute.

**Comment by hol353** [comment] 2020-05-18 02:21
Yep. Sounds good - lets do it.

**Closed** 2020-05-20 03:57 UTC
Labels: bug, interface/infrastructure
