### ISSUE TITLE
User Interface is slow to load a .apsimx file

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#2770] opened 2018-07-20 02:12 UTC
This is caused by deserialising .apsimx file to memory objects. For large .apsimx files (e.g. Tests/Validation/Wheat.apsim) this can take about 10 seconds or more.

The plan is to try and not deserialise the file upfront but instead to deserialise individual models when they are needed by the user as they click on nodes in the TreeView. The .apsimx will be loaded via XmlDocument.Load and the TreeView will be populated from the XmlDocument.

**Comment by hol430** [comment] 2018-10-25 04:45
Duplicate of #3215

**Closed by hol430** 2018-10-25 04:45 UTC
Labels: bug, interface/infrastructure
