### ISSUE TITLE
Met file path problems

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1783] opened 2017-07-10 05:36 UTC
When choosing met data, the UI often gets the path mixed up.  The file name seems to stay right, but it often changes the given path to that of the APSIM executable (ie the directory into which APSIM was installed).
It doesn't seem to do this all of the time.  But enough to make batch tasks difficult - the model fails to find met data from time to time.

**Comment by hol430** [comment] 2018-03-05 04:42
I've been able to reproduce this by opening an example, saving it to another location before doing anything else, and then looking at a weather node.

**Comment by hol430** [comment] 2019-10-30 05:12
Duplicate of #2371

**Closed by hol430** 2019-10-30 05:12 UTC
Labels: bug, interface/infrastructure
