### ISSUE TITLE
Morris error"Syntax error: Missing operand after '12' operator."

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5842] opened 2020-11-04 23:27 UTC
hi guys 
sorry its me again.
what does this**_"Syntax error: Missing operand after '12' operator."_** mean in Morris sensitivity ? 
thanks a lot  for help
![morris](https://user-images.githubusercontent.com/45214463/98178778-908d8c00-1f12-11eb-9bd2-eae04be4f4a6.PNG)

**Comment by hol430** [comment] 2020-11-04 23:31
Hi @masooandy - not sure off the top of my head. If you upload your .apsimx/.met files I'll take a look.

**Comment by masooandy** [comment] 2020-11-05 07:49
hi 


@hol430
here  they are and thanks for help.

**Comment by hol430** [comment] 2020-11-06 03:14
Thanks @masooandy. It's definitely caused by a bug in apsim, related to using a date (Clock.Today) as the variable name for aggregation. Probably no one has tried this before - the example file just uses a year, rather than an exact date. Anyway, I've fixed the bug in #5849, so after it's merged you should be able to update to the latest version and rerun your file and it should just work.

**Closed** 2020-11-08 21:33 UTC
Labels: bug, interface/infrastructure
