### ISSUE TITLE
Port the Classic prototype slope-aspect modifier of weather to Next Gen.

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#4240] opened 2019-10-04 00:13 UTC
The plan is to port the (unreleased) component developed by @rcichota to Next Gen. This would be a training task for Mike Rollo (AgResearch). Some GitHub discussion is needed to decide if it should be added into MicroMet or be a separate component. Will likely start this as a separate component so don't need an immediate decision.

**Comment by sarahcleary** [comment] 2019-11-02 11:41
@sno036 - should this issue for linked to https://github.com/APSIMInitiative/ApsimX/issues/4288?

**Comment by hol353** [comment] 2019-11-03 19:43
Duplicate of #4288 - closing this issue

**Closed by hol353** 2019-11-03 19:43 UTC
Labels: major, newfeature, science
