### ISSUE TITLE
Possible to modify crop genetic coefficnets?

### ISSUE THREAD

**Issue by qluo02** [APSIMInitiative/ApsimX#6194] opened 2021-02-24 00:11 UTC

**Comment by hol430** [comment] 2021-02-24 00:17
Duplicate of #6195.

**Closed by hol430** 2021-02-24 00:17 UTC

**Comment by qluo02** [comment] 2021-02-24 00:19
Dear apsimX users

Just wondering if possible to modify crop genetic coefficients for sensitivity studies in ApsimX. If yes, how? Unlike apsim classic crops models, the relevant crop models are inaccessible for users in apsimX. 

Looking forward to your great support!
