### ISSUE TITLE
Renaming of a node in tree changes the name on the wrong node

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#8473] opened 2023-11-29 09:19 UTC
### What happened?

It is difficult to explain the exact sequence of actions to reproduce the issue, however...

I added a cultivar to my crop, then renamed it to match my new cultivar name.
I did further work and then renamed a series in a graph.  The model didn't run because it said my cultivar didn't exist.
When I checked, the cultivar had been renamed to the graph series I had tried to rename.

I keep finding that renaming a node can change the name of the parent node.  It appears that it can also change the name of whatever you have previously worked with.  It seems to be remembering an incorrect path (ie it thinks you are working on a different node).

### What Operating System are you on?

Windows

**Comment by HamishBrownPFR** [comment] 2023-11-29 19:25
I was encountering a similar problem last week but it was fixed with a recent merge https://github.com/APSIMInitiative/ApsimX/pull/8458

**Comment by HamishBrownPFR** [comment] 2023-12-01 02:24
I have started encountering this again now too

**Comment by peter-devoil** [comment] 2023-12-01 04:10
I've updated this morning and still seeing it.

**Comment by par456** [comment] 2023-12-03 23:25
Do you have an idea exactly what actions you took before it renamed the wrong node? 

I could try to patch this because I think I know where the problem is, but I've not been able to replicate it on my end when just clicking around the GUI, which makes it harder to know if what I change will actually fix it on your end.

**Closed** 2024-01-09 05:56 UTC
Labels: bug
