### ISSUE TITLE
Figures in the simulation

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3564] opened 2019-03-04 00:23 UTC
Have a simulation under experiment. 

All points and/or lines will be shown if no factors are set for Type, Line Type, marker type and Colour. See figure below which is working before. 

![image](https://user-images.githubusercontent.com/1657381/53704291-33048a80-3e67-11e9-9cc6-bdd0280bb371.png)

The figure shows only the current simulation if the factor is set. 

![image](https://user-images.githubusercontent.com/1657381/53704328-91316d80-3e67-11e9-84b3-bdb73ac88981.png)

**Comment by hol430** [comment] 2019-03-04 23:55
I'm unable to reproduce this...can you upload an .apsimx file which demonstrates the problem?

**Comment by byzheng** [comment] 2019-03-06 00:36
Attached an example: 

Check figure "Biomass fixed color". I expect to show only one experiment, not all two experiment.

[test.zip](https://github.com/APSIMInitiative/ApsimX/files/2933764/test.zip)

**Comment by hol430** [comment] 2019-03-07 00:24
It only shows data from one experiment for me:

![image](https://user-images.githubusercontent.com/36427516/53923143-e1f0d280-40c2-11e9-8fe6-733207436e4f.png)

**Comment by byzheng** [comment] 2019-03-07 00:35
@hol430 it is wired. It seems this bug is fixed after I update into latest version.

**Comment by hol430** [comment] 2019-03-07 01:16
Yeah I've made some changes to the graphing code in the last few weeks, one of those changes must have fixed this problem.

Closing this now as it has been resolved.

**Closed by hol430** 2019-03-07 01:16 UTC
Labels: bug, interface/infrastructure
