### ISSUE TITLE
An error is reported when the Apsim-Server is started

### ISSUE THREAD

**Issue by xiangyi-wang** [APSIMInitiative/ApsimX#7508] opened 2022-09-15 03:25 UTC
![image](https://user-images.githubusercontent.com/22881957/190306554-c94cfbc8-eaa4-4cc8-a390-6c89e427c9d7.png)
Deleting apsim-server.deps.json can be used normally

**Comment by par456** [comment] 2023-04-24 06:00
I could not reproduce this on the current build, server started correctly when given proper arguments. The above error is looking for .net 3.0 libraries, so this may be been resolved when we stopped targeting .net 3.1

Closing for now.

**Closed by par456** 2023-04-24 06:00 UTC
Labels: bug, interface/infrastructure
