### ISSUE TITLE
Errors compiling under Debian Buster

### ISSUE THREAD

**Issue by jal-frezie** [APSIMInitiative/ApsimX#4246] opened 2019-10-09 14:48 UTC
Tried to update to latest Git version before reporting another error. I went:
git pull
sudo nuget update -self
nuget restore
(nuget reports no change)
monodevelop

and tried rebuild, then build, ApsimX.
It stopped with 3 errors, 2 warnings. Attached logfile was produced.

**Comment by jal-frezie** [comment] 2019-10-09 14:52
[Build Output 3:45 pm 2019-10-09.binlog.gz](https://github.com/APSIMInitiative/ApsimX/files/3707982/Build.Output.3.45.pm.2019-10-09.binlog.gz)

**Comment by jal-frezie** [comment] 2019-12-17 10:19
I'm still getting something very similar to this with the latest version -- but it does seem to run OK afterwards anyway!
[Build Output 10:15 am 2019-12-17.binlog.gz](https://github.com/APSIMInitiative/ApsimX/files/3972701/Build.Output.10.15.am.2019-12-17.binlog.gz)

**Comment by hol430** [comment] 2019-12-18 00:24
Interesting - it's almost as if the compiler has found a different version of the gtk# modules. Which version of the gtk-sharp2 and mono packages do you have installed?

I'm able to compile and run without problems on Debian stretch with these packages:

```
~/code/ApsimX $ apt list gtk-sharp2
Listing... Done
gtk-sharp2/stable-stretch,now 2.12.45-0xamarin17+debian9b1 all [installed]
N: There is 1 additional version. Please use the '-a' switch to see it
~/code/ApsimX $ xbuild /version
XBuild Engine Version 14.0
Mono, Version 6.6.0.161
Copyright (C) 2005-2013 Various Mono authors
```

**Comment by jal-frezie** [comment] 2019-12-18 08:32
mono-runtime: 6.6.0.161-0xamarin7+debian9b1
monodevelop: 7.8.4.1-0xamarin6+debian9b1
gtk-sharp2: 2.12.45-0xamarin17+debian9b1
...all seems the same as yours, except I am running Debian Buster

**Comment by hol430** [comment] 2020-03-22 22:52
Closing this as a duplicate of #4772.

**Closed by hol430** 2020-03-22 22:52 UTC
Labels: bug, interface/infrastructure
