### ISSUE TITLE
InitialN not impacting growth simulation

### ISSUE THREAD

**Issue by iMarang** [APSIMInitiative/ApsimX#6505] opened 2021-05-27 02:26 UTC
![ver8_v13_yield](https://user-images.githubusercontent.com/22802468/119756120-6cad8a00-bee6-11eb-9ce8-09c02735db1e.png)
[ver8_and_ver13_runfiles.zip](https://github.com/APSIMInitiative/ApsimX/files/6550684/ver8_and_ver13_runfiles.zip)

I’ve run multiple iterations of this DA framework I’ve put together, but found something odd.  InitialN doesn’t seem to have any impact on yield or leaf N concentration.  Bit of backstory, I’ve had soil tests done by an external lab prior to sowing and entered the Extractable Nitrate N value into the APSIM runs under ‘InitialN’ in the Soil submodule.  I converted them initially incorrectly by a factor of 10 less than it should be (v8 attached), and then updated (v13 attached).  (BTW, I realise the script I used to create the 540 run files was originally adding the wrong entries at the end of the ‘InitialN’ component in v8 also, but no errors were thrown.)  When I’ve fixed this, run them both and checked the results there is no difference in performance between the two (see plot).  More BTW than you can poke a stick at … LCCC in the plot stands for Lin’s conchordance correlation coefficient.
 
Have I entered them incorrectly in the run file?  Is it not the correct parameter to enter?  Is this the old ‘read only’ chestnut I had with the cultivar parameters and so needs to be in a ‘Replacement’ component?

**Comment by BrianCollinss** [comment] 2021-05-27 02:37
Hi @iMarang . It seems the N columns in InitialN are empty. Am I looking at the wrong thing?

![image](https://user-images.githubusercontent.com/39573622/119757475-57d1f600-bee8-11eb-9120-27f2e7397c72.png)

**Comment by iMarang** [comment] 2021-05-27 02:44
Intriguing.  Where are you seeing that?  When I check the Field=>Soil=>InitialN I see the NO3N column filled.  Also, the naming is different in your screenshot? 

<img width="817" alt="Screen Shot 2021-05-27 at 12 41 41 pm" src="https://user-images.githubusercontent.com/22802468/119757966-14c45280-bee9-11eb-8ed1-1a3e0eb8a420.png">
<img width="831" alt="Screen Shot 2021-05-27 at 12 40 53 pm" src="https://user-images.githubusercontent.com/22802468/119757971-15f57f80-bee9-11eb-8627-4f8beae2d42f.png">

**Comment by BrianCollinss** [comment] 2021-05-27 02:45
Are you using the latest version (from GitHub)?

**Comment by iMarang** [comment] 2021-05-27 03:17
That is a damn good question, I suspect not.  How would I find out?  Also, how would I upgrade it without breaking my macOS install?  When I've tried clicking the 'Upgrade' option on the APSIMx control panel it just comes up with "You are on a custom build.  You cannot upgrade"

**Comment by BrianCollinss** [comment] 2021-05-27 03:53
Yeah. You need the source code and compile it to get the latest version. There should be some instructions here: https://apsimnextgeneration.netlify.app/modeldocumentation/

**Comment by BrianCollinss** [comment] 2021-05-27 04:06
BTW, I am not sure if your N issue has anything to do with this as you are using an older version and have the N values in InitialN object. But it is worth looking at the newer versions.

**Comment by iMarang** [comment] 2021-05-27 04:10
Thanks Brian, I can try the newer version.  I'd just like to confirm two things though, the NO3N in my InitialN and NO3 in yours should be broadly equivalent in terms of operational usage by the model, is that correct? Also, how do I check what version I have?

**Comment by BrianCollinss** [comment] 2021-05-27 04:11
TBH I have never used the released version. I always compile the source code. I am also not familiar with Solution object. @hol430 could you please help our friend?

**Comment by iMarang** [comment] 2021-05-27 04:51
Understandable, I wouldn't touch the .sln with a barge pole if I could avoid it, though it's been pretty seamless (apart from some spurious errors when running). Any fresh download and rebuild will affect the system and model paths etc for my existing python framework implementation.  I'd prefer to avoid this if possible as you can imagine I'm sure.  

A couple of things while I troubleshoot this or wait for Mr Holzworthy though ... the documentation page (https://apsimnextgeneration.netlify.app/modeldocumentation/) doesn't have installation instructions.  Am I missing something?  Also, the Apsimx page registration page link for downloading binaries goes to an 'APSIM upgrades' page (https://apsimdev.apsim.info/APSIM.Registration.Portal/Main.aspx) which lists only 7.x versions (mostly small Windows updates) from what I can see.  Should this list the Apsimx versions instead?

**Comment by hol430** [comment] 2021-05-30 23:41
I think the problem is that the NO3 value in the Chemical node is overwriting the value in the initial N node. If I set the initial no3 amounts in the chemical node, I start getting different yields between the two simulations. (Note: chemical node expects no3 in ppm, not kgha.)

@hol353 is this the intended behaviour? In the soil standardiser code it looks like we're only using the no3 in chemical if it's provided (ie if it's not null)...but earlier in the soil standardiser we set the chemical node's no3 to a default value of 0.1ppm in each layer if no value is provided (ie if the property is null). Actually, a better question might be why do we even have two different ways to set the initial no3 amount as this is just plain confusing.

> the Apsimx page registration page link for downloading binaries goes to an 'APSIM upgrades' page (https://apsimdev.apsim.info/APSIM.Registration.Portal/Main.aspx) which lists only 7.x versions (mostly small Windows updates) from what I can see.

There should be a dropdown at the top of the page which lets you select next gen. This is the place to go for the official builds - if you use one of these builds, you should be able to upgrade from inside the GUI.

> Also, how do I check what version I have?

If you've compiled your own build then the only thing you have to go on is the git logs. You can run `git log -1` from inside the apsimx directory, which will tell you the most recent commit, which will include a timestamp. This should give you a general idea of the vintage of your build, although it can be tricky to work out to which of the binary releases it corresponds.

**Comment by iMarang** [comment] 2021-05-31 01:02
Ah, thanks @hol430, that makes sense.  I'll update and retry later today.  It would be good to know whether this is intended or if gremlins are lurking as I've tried this same situation in ver 7.x over 40 years and found similar yields (but not exactly the same) over the full simulation timeframe.

OK, great, I've just been differentiating the versions on date downloaded as I don't use it for actual troubleshooting like you A-Team guys (are you the BA Baracus?).  Good to know how to access next gen options officially rather than as custom builds.

**Comment by iMarang** [comment] 2021-06-01 08:36
I've rerun the test and can confirm the Chemical entries do change the yield values.  Interestingly, for all but the 0 and a few of the 50 kg ha-1 N treatments the added chemical data strongly reduces the yield (average observed yield for all treatments was between 4900-6100 kg ha-1).

![ver13_v15_yield](https://user-images.githubusercontent.com/22802468/120290447-b1ca2580-c305-11eb-981d-ddf8ebdbb865.png)


The plot is comparing yield for the previous version (with the initialN populated) and the new one (with the chemical node populated) for 10 weather ensemble members.  I've kept only the first iteration, lab tested soil conditions, and default APSIM physics.

Question though, I've added all soil test data to the Chemical node, not the InitialN node.  Is this correct?  Sample .apsimx and .met files attached 
[ver13_wd_200_MED_ens5_default.apsimx.zip](https://github.com/APSIMInitiative/ApsimX/files/6574717/ver13_wd_200_MED_ens5_default.apsimx.zip)
[ver15_wd_200_MED_ens5_default.apsimx.zip](https://github.com/APSIMInitiative/ApsimX/files/6574719/ver15_wd_200_MED_ens5_default.apsimx.zip)

[NarrabriAvg20_2020_ens5.met.zip](https://github.com/APSIMInitiative/ApsimX/files/6574658/NarrabriAvg20_2020_ens5.met.zip)

**Comment by hol430** [comment] 2021-06-14 23:16
How are you modifying your initial N? Are you using an external script to generate .apsimx files? If so, could you upload your script? The way that you apply the initial N here may be the culprit, as I just put together a quick experiment with variable N applications via fertiliser and my yield was varying quite a bit.

**Comment by iMarang** [comment] 2021-06-15 01:53
Yes, it's done via a script.  I've tested adding the soil test data to the template in both the InitialN and Chemical nodes (_soilTestBoth), Chemist only (_soilTestChemist) and InitialN only (_soilTestInitialN).  Both those with the soil test data in Chemical showed 5370.036 kg while the InitialN only one got 3586.867 kg.

Attached are the 3 sample tests, the .met file to run them and the python code to create the templates.

[testInitialN_files.zip](https://github.com/APSIMInitiative/ApsimX/files/6652194/testInitialN_files.zip)

**Comment by hol430** [comment] 2021-06-15 03:34
Nice python script - I'll be that was fun to write :). The _soilTestChemical file is setting the initial n the "right" way. The _soilTestInitialN simulation effectively has very low initial N which is why it has a lower yield.

I'm not 100% sure of the problem here - the simulation with the higher initial N has the higher yield. If your yields are differening less than you expect with respect to initial N amount, then perhaps your crop is not so n-limited. If that's the case, you could try adding an auto irrigation script from the manager toolbox and see if that has an impact.

**Comment by iMarang** [comment] 2021-06-16 00:42
Fun is not the word I would use ;) I'm tinkering with an idea for automating json path finding to connect the dots and save the laborious manual work on future runs, but for now I'll run with the teeth gnashing.

The problem isn't that the yields are wrong, the problem is the purpose of the 'InitialN' node.  When you hover over it the tooltip shows "Sample". If it isn't used for describing a soil test sample prior to a run, I'm not sure what it does?   For my work, I'll just run with the Chemical node, but for future work perhaps the node can be just dropped if it isn't used?

**Comment by hol430** [comment] 2021-06-16 03:22
@hol353 see above. Could you confirm how we are supposed to set the initial N? The values in the chemical node will always overwrite the values in the sample, even if no values are provided in the chemical node. This seems like a bug but it also seems strange to have two ways of setting this in the first place.

**Comment by hol353** [comment] 2021-06-16 03:53
If you put values in the sample node it is supposed to override any values in the chemical node. This has changed many times over the last few years - not surprised there is a bug. I wonder whether we just get rid of the sample node completely. The problem with that is there is currently nowhere to put starting water by layer. Perhaps we could add that to InitialWater as an option.

**Comment by iMarang** [comment] 2021-06-16 04:52
From a user perspective, adding the Soil Water by layer into the InitialWater node makes a lot of sense.

**Comment by hol353** [comment] 2023-05-22 04:44
Closing as this issue is very old. Unsure if the initial problem has been resolved or not.

**Closed by hol353** 2023-05-22 04:44 UTC
Labels: bug, interface/infrastructure
