### ISSUE TITLE
SplitScreen not resizing panes properly

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#4943] opened 2020-03-23 23:19 UTC
![image](https://user-images.githubusercontent.com/635772/77371812-e2ccd300-6daf-11ea-9fca-a7bfee36f512.png)

In splitscreen - move the splitter to the left, going far enough to make the scrollbar appear and then a bit further. Then without letting the splitter go, start moving back to the right - the window below is then overlaid across the top of the splitter and right hand window.

**Comment by jbrider** [comment] 2020-03-23 23:23
It occurs if the left side PropertyPresenter is a graph

**Comment by zur003** [comment] 2020-03-24 00:29
Looks like it might be a problem in OxyPlot. I'm seeing this only with charts. Note that only some components of the chart are mis-behaving.
![image](https://user-images.githubusercontent.com/11879340/77375797-ad7db080-6dc2-11ea-91af-4ab957219385.png)

**Comment by hol430** [comment] 2020-05-14 05:51
I'm unable to create a simple, standalone program to reproduce this, even if it has the same (or almost the same) widget hierarchy and settings, which leads me to suspect that this might be due to something in our code after all.

Interestingly, this doesn't seem to occur on the gtk3/.net core branch.

**Comment by hol430** [comment] 2022-01-11 01:49
Closing - this is not a problem in gtk3 builds.

**Closed by hol430** 2022-01-11 01:49 UTC
Labels: bug, interface/infrastructure
