### ISSUE TITLE
Default text size for Model Presenter

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#5867] opened 2020-11-17 03:39 UTC
The default text size displayed in the Model Presenter seems a bit oversized.
I haven't changed any config settings for themes or fonts.

![image](https://user-images.githubusercontent.com/635772/99343753-3dd0ae80-28da-11eb-83ff-05c5c18522da.png)

**Comment by hol430** [comment] 2020-11-17 04:07
Seems to be a bug in the markdown parser we're using. When there's only a single linefeed after the title, it treats the following paragraph as part of the title. This is not the only issue I've noticed with this parser - I wonder if it's worth changing to a different one.

**Comment by jbrider** [comment] 2020-11-17 04:47
Is the one we're using something we can feed back the bug to them?
Sounds like it's getting confused with rules for markdown syntax which requires the extra line.

**Comment by hol430** [comment] 2020-11-17 05:04
I've filed a bug report for a different issue related to the markdown parser, and I would have fixed it myself already (or tried to), but building/debugging the parser requires a more recent windows than what I have installed. It looks like they're working on moving to markdig anyway, so in theory this issue might fix itself in time. In the meantime, we could always edit the summary on the affected models...which is probably most of them.

**Comment by hol430** [comment] 2020-12-21 06:00
@hol353 @hut104 this will be a good one to look at during the refactoring week. The problem here is that the documentation UI will strip newlines from the model descriptions before showing them in the UI. This is because many model descriptions are wrapped at 80-120ish characters. If we don't strip newlines, then it looks rather odd in the UI. This means if your description looks like this:

```
/// <summary>
/// # [Name]
/// The soil nutrient model includes functionality for simulating pools of organmic matter and mineral nitrogen.  The processes for each are described below.
/// ## Soil Nutrient Model Structure
```

Then the end result passed to the markdown parser will be

```
# [Name] The soil nutrient model includes functionality for simulating pools of organmic matter and mineral nitrogen.  The processes for each are described below. ## Soil Nutrient Model Structure
```

Which is why the markdown parser thinks it's all a title...as far as the parser is concerned, it *is* all a title. Not sure what the solution is...surely we want to allow descriptions to be wrapped in the code. The alternative what has been done to the nutrient description, which is extremely hard to read if you have line wrapping disabled in your text editor. Maybe we strip out single newlines, but leave double newline as-is. (If you pass paragraphs separated by a single newline to the parser, it will likely parse it as a single paragraph block.)

**Comment by hol353** [comment] 2021-01-22 02:26
What view are we using to display the markdown? Are we using our MarkDownView? If so then I don't understand what the issue is.  Surely MarkDownView doesn't care about new lines. I would have thought MarkDownView would show the same doco as in the documentation.

**Closed** 2021-03-11 21:57 UTC
Labels: bug, interface/infrastructure
