### ISSUE TITLE
Error in either ControlledEnvironment or Weather?

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#1065] opened 2016-08-22 02:11 UTC
ControlledEnvironment when used with Slurp and no changes in LAI etc. should return the same water demand every day but something a little weird is going on.  The plot below is for a latitude of -45 and the simulation goes from 1 Jan to 31 Mar.  By my thinking EP should only change with date if daylength is changing (this would cause the radiation intensity to increase as daylength shortens as summer ends).  But ... daylength is an input in the component (12 hours in this example) and secondly what is going on with the abrupt change on the first day of the month.  It is sort of like the daylength (or something else) is changing during the month but is then being updated to the correct values each first of the month.  Strange!?!

Maximum Air Temperature (oC)    15
Minimum Air Temperature (oC)    15
Rainfall (mm)   0
Solar Radiation (MJ/m2/d)   15
Pan Evaporation (mm)    3
Vapour Pressure (hPa)   2
Wind Speed (m/s)    3
CO2 concentration of the air (ppm)  350
Latitude (deg)  -45
Day Length (h)  12

![capture](https://cloud.githubusercontent.com/assets/12176269/17841918/b2b0f63e-6871-11e6-9636-a3462bb89d3f.JPG)

**Comment by hol353** [comment] 2020-09-29 01:41
I've reproduced the changing EP over time here:

[Slurp.zip](https://github.com/APSIMInitiative/ApsimX/files/5295844/Slurp.zip)

I don't see the abrupt change in EP at the start of each month. Perhaps that has been fixed. My chart looks is pasted below.

The reason EP changes is because MicroClimate calculates its own day length (2 of them actually) and doesn't get it from weather:
```c#
dayLengthLight = MathUtilities.DayLength(clock.Today.DayOfYear, sunSetAngle, weather.Latitude);
dayLengthEvap = MathUtilities.DayLength(clock.Today.DayOfYear, sunAngleNetPositiveRadiation, weather.Latitude);
dayLengthEvap = Math.Max(dayLengthEvap, (dayLengthLight * 2.0 / 3.0));
           
```

Closing this for now as I'm unsure what the expected behaviour is.

![image](https://user-images.githubusercontent.com/1943827/94502803-4eed2f80-0248-11eb-8c3f-d6debc3fac57.png)

**Closed by hol353** 2020-09-29 01:41 UTC
Labels: bug, science
