### ISSUE TITLE
PMF organs should not resolve [Link] for functions when there is no exact match

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#350] opened 2015-09-10 08:55 UTC
PMF is finding links for functions that don't exist.  This bug has been fixed once before so not sure why it has come back.

The test I used was to rename the NitrogenDemandSwitch on the Root organ.  to NitrogenDemandSwitch123412.  In the code this is not optional so should throw an object reference error.  But it doesn't it just finds another function and uses its value,

![image](https://cloud.githubusercontent.com/assets/7295858/9784228/1af2c59a-57fe-11e5-8e68-f2d8474f83fd.png)

**Comment by hol353** [comment] 2015-09-11 04:02
The problem is that we want different behaviour depending on whether the link is a function or not. In the above example, yes we do want it to match the type (IFunction) and the name (NitrogenDemandSwitch) otherwise throw an error.

In lots of PMF functions (e.g. AirTemperatureFunction.cs) and in other models we have this:

        [Link]
        protected IWeather MetData = null;

In this case we want to only match on the type (IWeather) and not the name (MetData). I guess we could make a special case for functions but I don't like special cases.

Any suggestions on how to get around this?

**Comment by HamishBrownPFR** [comment] 2015-09-11 04:23
I can't think of anything better but I not a very good programmer.

**Comment by hol353** [comment] 2015-09-11 05:29
So I've got a fix for this but now PMF crops give this error:

N Mass balance violated!!!!.  Daily Plant N increment is greater than N supply

I'm guessing that it has worked in the past with the wrong functions linked in. I need to think of a way to debug this. Any suggestions?

**Comment by HamishBrownPFR** [comment] 2015-09-12 09:38
I suspected there might be some things like that going on.

I can debug that if you want.  What is the url for the branch you have this on

**Comment by hol353** [comment] 2015-09-13 22:29
Branch is here: https://github.com/hol353/ApsimX/tree/resolvelink. I only modified one file. Apsim.cs

**Closed** 2015-10-12 22:48 UTC
