### ISSUE TITLE
Cannot name an item using the same term defining a model in Replacements

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#6333] opened 2021-04-09 05:18 UTC
An error (Object reference not set to an instance of an object.) is thrown when attempting to run a simulation in which one or more items (e.g. graph or series) has the same name as a model in the Replacements.
We noticed this issue when doing simulations using two crops (grapevine and lucerne), in there we had a lot of graphs and/or their series named after the crops (which I'd think is a fairly common thing to do), however we cannot run the simulation if the crops are in the Replacements (which is where we want them as they are still under development). After isolating the issue I tried with only one crop, and even using an already released crop. Still get the same error.
It seems APSIM cannot find the path to the plant's submodels (leaf, phenology, etc.), which are of course not present on a graph...  So this must be related to #4423 
The immediate solution was to rename all graphs with something like 'LucerneCrop', but this is obviously a lot of work and not ideal as naming the graph series after the crop would be best/more intuitive when inspecting the graphs. E.g. from one of our graphs 
![image](https://user-images.githubusercontent.com/12175986/114131692-2d87a180-9957-11eb-9c53-f3871f3b8f5d.png)

![image](https://user-images.githubusercontent.com/12175986/114131832-6aec2f00-9957-11eb-970f-2254232d7dca.png)

**Comment by hol430** [comment] 2021-04-11 23:50
For better or worse, the replacements model is currently designed to replace all matching models in the simulation. In cases like this, that's going to cause problems. This is related to a number of other issues such as the scoping one you mentioned - sometime this year it would be good to resolve a few of these but it will require us to rethink large parts of the infrastructure. As a temporary workaround I might suggest naming your series "lucerne " (ie lucerne and then a space). For now, I'm going to improve this error message to make it a little more obvious what's gone wrong.

**Comment by rcichota** [comment] 2021-04-19 09:25
I was wondering whether searching for type and name would help finding the right model?

**Comment by rcichota** [comment] 2021-04-19 09:28
Changing the error message will improve finding work arounds in the future, thanks.
I have used renaming the graphs (I called 'lucernes', really don't like using spaces, too easy to miss them and get further confusion)

**Comment by hol430** [comment] 2021-04-19 22:20
I believe it's been deliberately designed to not look for type, so that you can have, for example, an experiment where one of the factors switches between soilwat and swim - in order for this to work, the infrastructure has to do a name lookup but not check the type of the model being replaced.

**Comment by hol353** [comment] 2023-02-17 03:38
Closing. For now, Replacements doesn't consider model type when replacing models. This is by design for the use case that @hol430 outlines above.

**Closed** 2023-05-22 22:47 UTC
Labels: bug, interface/infrastructure
