### ISSUE TITLE
deep soil layers from array variable reported out of order

### ISSUE THREAD

**Issue by AllanPeake** [APSIMInitiative/ApsimX#2685] opened 2018-06-12 06:08 UTC
Layers 7-10 from my soil variable array are being reported out of order, away from layers 1-6

**Comment by hol430** [comment] 2020-12-21 02:27
I'm going to close this one, as I can't reproduce it. Given the age of this issue it's entirely possible that this has been fixed in the meantime. If you see this happening again, feel free to reopen or open a new issue.

**Closed** 2020-12-21 02:28 UTC
Labels: bug, interface/infrastructure
