### ISSUE TITLE
"Object not set..." when clicking away from a model which uses an editor component

### ISSUE THREAD

**Issue by hol430** [APSIMInitiative/ApsimX#7111] opened 2022-02-18 02:04 UTC
When clicking away from a model which uses a CodeView in the UI (ie report, manager, cultivar, ...), a null reference exception is generated.

**Comment by sno036** [comment] 2022-02-20 20:55
@hol430  - is this in the highest priority list to fix?

**Comment by zur003** [comment] 2022-02-20 22:46
@hol430 - The problem here seems to involve some dark corners of Gtk# object destruction, but I think at least part of the problem is in IntellisenseView.cs where we have in the Cleanup routine:

>             if (completionForm.IsRealized)
>                 completionForm.Dispose();
>             completionView.Dispose();
>             completionForm.Dispose();
>             completionForm = null;


Note that this can result in completionForm.Dispose() being called twice, which doesn't seem like a good thing to do.

But that's not the whole problem, and there are bits I don't fully understand. I find that if I open the Standard Toolbox and scroll through the list of cultivars, that instances of EditorView are being created, but seemingly not destroyed. I find it all rather confusing.

**Comment by hol430** [comment] 2022-02-20 22:58
Yep - the problem appeared when we updated the version of the GtkSharp package (which also included an update of the native libs as well).

There may be multiple problems here - the one I observed was at CodeView.cs when we attempt to remove some event handlers from an object which has already been disposed of. I suspect something has changed in the object destruction in gtk as you say. It may be that we were relying on undefined behaviour in the past. Perhaps we need to, in general, detach event handlers from gtk objects sooner (ie before the Destroyed event is fired).

**Comment by zur003** [comment] 2022-02-21 00:50
And then there is the rather confusing distinction between "Dispose" and "Destroy". As Gtk evolves, it appears to be heading away from the use of "Destroy" (I think), but the relationship between the two is fuzzy and seems to sometimes change with different versions of Gtk. I may experiment a bit with overriding GObject.Dispose rather than relying on the Destroyed signal for doing memory cleanup, and see what happens.

**Comment by hol430** [comment] 2022-02-21 02:14
From the docs for [gtk_widget_destroy](https://developer-old.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-destroy):

> It's important to notice that [gtk_widget_destroy()](https://developer-old.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-destroy) will only cause the widget to be finalized if no additional references, acquired using g_object_ref(), are held on it. In case additional references are in place, the widget will be in an "inert" state after calling this function; widget will still point to valid memory, allowing you to release the references you hold, but you may not query the widget's own state.
>
> You should typically call this function on top level widgets, and rarely on child widgets.

It would appear that [GtkSharp handles this abstraction for us](https://github.com/GtkSharp/GtkSharp/blob/master/Source/Libs/GtkSharp/Widget.cs#L396-L414), and disposing of a widget by calling `Dispose()` will cause the widget to be automatically destroyed if and only if the widget is a top-level widget. So if we want to execute some cleanup code in our view objects, we may need to move away from the destroy signal as you say. Or manually call `Destroy()`, as I think we used to do.

**Comment by sno036** [comment] 2022-02-22 01:07
@hol430  - in Report typing the {.} after [Soil].Nutrient generates a null reference error. It is 'continuable'. Is this the same error as this issue?

![image](https://user-images.githubusercontent.com/12176269/155044933-3af27fd0-56e1-4805-8050-17f1fa2c1662.png)

**Comment by hol430** [comment] 2022-02-22 01:57
Different error - there are a lot of reasons that one might encounter this exception.

**Comment by zur003** [comment] 2022-02-23 10:59
@hol430 - I've been looking into this, and am seeing a lot of ugliness. I'm still trying to make sense of it all, but the problems seem to revolve largely around the process of destroying objects in Gtk#. Have a look at [https://github.com/GtkSharp/GtkSharp/issues/82](https://github.com/GtkSharp/GtkSharp/issues/82) for a discussion related to some of these issues. Note that it appears that, at least some of the time, one needs to call BOTH Destroy and Dispose to get things cleaned up. 

Also, the mechanism used for handling signals overall has changed from earlier versions, so the DetachHandlers routine in GktUtilities.cs is no longer working. This means we're not always cleaning up all references, and we're getting memory leaks as a result. I have a patch to fix that problem.

However, there are other issues. The "destroy" signal is now treated as a special case. Other signals have pointers to their handling delegates maintained by the Object they are associated with, but Widget "destroy" signal handlers are all kept in a single static global dictionary. It uses the GLIb Handle of the widget as a key in the dictionary to look up the handling delegate. The entries in this dictionary get deleted when the widget finally receives and acts on the "destroy" event. That's usually OK, but what I think is happening is that in cases where we've defined a handler for "destroy" (which we do commonly to ensure cleanup), the problems with Dispose vs. Destroy means that the "destroy" event is never being sent, even though the associated widget has been disposed. Now I'm not really sure how Gtk Handles are allocated, but I know they are actually IntPtrs. I think what might be happening is that a widget has been disposed, but its "destroy" handler is still in the dictionary. A new widget may get created using the same memory block that the disposed widget once occupied (thereby recycling the old handle), and when the new widget gets destroyed, it looks things up in the dictionary using that handle and invokes a delegate intended for something completely different. Or something like that...

I'm also finding that a lot of cleanup that ought to be occurring isn't happening. Often these are signal handlers that are added but never removed. These references get in the way of the garbage collection system, so we're probably leaking memory in a number of places. Cleaning this up may take a while. 

I'm wondering whether it would be feasible to implement the IDisposable interface in ViewBase, so that rather than calling Destroy and/or Dispose on the main widget in a view to close it, we would instead call the view's Dispose, and have it detach all handlers and Destroy the main widget. Views needing additional cleanup could override the Dispose function to do whatever else might be needed.

There may be a lot of stuff that needs fixing here....

**Comment by sno036** [comment] 2022-02-24 21:26
Got this today and @hol353 thought it might assist. On the tip revision of the master branch.

![image](https://user-images.githubusercontent.com/12176269/155610358-bee1e479-6ac5-4944-8752-d82a4ac94a30.png)

**Comment by hol430** [comment] 2022-02-24 23:58
Hi @zur003 - thanks for looking into this. The problem of destroy not being called can be somewhat remedied by changing ExplorerView to destroy the right-hand panel's main widget when changing the right-hand panel in `AddRightHandView()` (e.g. see ExplorerView.cs:65 - we could call Destroy() here). `Destroy()` will recursively destroy all child widgets, so this allows the views to receive the destroy signal and do their cleanup. That being said, I also think that our reliance on the destroy signal may not necessarily be a good thing and that it may be in our best interests to move away from this. Implementing `IDisposable` on ViewBase was my thought as well and might be a good way to solve this problem. A supplementary option might be a code linter (e.g. stylecop) configured to ensure that we don't forget to dispose of our IDisposable objects. Either way, I think we definitely need to be more consistent with the way we handle the unmanaged resources here.

**Comment by zur003** [comment] 2022-02-25 00:45
@hol430 - I've had a go at this, and implementing `IDisposable` in ViewBase seems to work well, without necessarily requiring massive changes. I have the disposal logic detach any signal handlers (other than 'destroy') from the main widget and its children, and then call Destroy on the main widget. With this arrangement, `AddRightHandView()` in ExplorerView.cs can simply call `CurrentRightHandView.Dispose()`.  Current cleanup calls of the form `_view_.MainWidget.Dispose()` become `_view_.Dispose()`. Any old cleanup logic relying on receiving the 'destroy' signal will still be invoked, but could (and probably should) be replaced with an override of Dispose, but that can be done gradually. One advantage of this approach is that it puts all calls to Destroy in a single place, so if Gtk# changes the way they handle widget destruction (again), we should be able to accommodate that more easily.

**Comment by zur003** [comment] 2022-03-11 04:46
PR #7136, which was committed a few days ago, has resolved the original problem of "object not set" errors (I hope!). There is still work to be done to resolve a few memory leaks, but I think that is best done as a separate Issue, so I'm going to close this one.

**Closed by zur003** 2022-03-11 04:46 UTC
Labels: bug, interface/infrastructure
