### ISSUE TITLE
Problems identified with move to .Net Core GTK#3

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6139] opened 2021-02-10 02:50 UTC
I thought it might be worth having this issue so we can all flag issues and fixes for problems identified as we start to run with netcoreapp3.1

**Comment by lie112** [comment] 2021-02-10 02:53
There's a known bug with core when trying to to open a url from System.Diagnostics.Process.Start() that we have been using.
[Here's the fix](https://brockallen.com/2016/09/24/process-start-for-urls-on-net-core/), but we should have this somewhere everyone can access rather than duplicate code wherever we need to open a url from the UI.

`        public static void OpenBrowser(string url)
        {
            try
            {
                System.Diagnostics.Process.Start(url);
            }
            catch
            {
                // hack because of this: https://github.com/dotnet/corefx/issues/10361
                if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
                {
                    url = url.Replace("&", "^&");
                    System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("cmd", $"/c start {url}") { CreateNoWindow = true });
                }
                else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
                {
                    System.Diagnostics.Process.Start("xdg-open", url);
                }
                else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
                {
                    System.Diagnostics.Process.Start("open", url);
                }
                else
                {
                    throw;
                }
            }
        }`

**Comment by hol430** [comment] 2021-02-10 03:01
Is this fixed by setting just UseShellExecute on the Process object to true?

(For code formatting, there's a handy cheatsheet for [github markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet))

**Comment by lie112** [comment] 2021-02-10 03:40
Must say I do like the look and feel of the core version. Much more professional.

**Comment by lie112** [comment] 2021-02-10 03:48
I'm not sure how to set the UseShellExecute on the ProcessInfo when we don't know the default app being used to open the url.

**Comment by lie112** [comment] 2021-02-10 03:50
Shall I create a new issue for each problem I am facing or happy to address all related here?

**Comment by hol430** [comment] 2021-02-10 03:52
Probably put them all here, I expect there will be quite a few problems :). By UseShellExecute, I mean setting `Process.StartInfo.UseShellExecute = true;`

**Comment by lie112** [comment] 2021-02-10 04:42
Yep. Once I found out how to get the ProcessStartInfo for a url, changing UseShellExecute to true fixed the problem.
IGNORE fix above.

**Comment by lie112** [comment] 2021-02-10 04:55
MarkdownView appears to display links in a very light colour (maybe dark theme) on white light theme background.
`ForegroundGdk = (ViewBase.MasterView as ViewBase).MainWidget.GetBackgroundColour(StateType.Selected);`

**Comment by lie112** [comment] 2021-02-10 23:49
I can run APSIM in .netcoreapp3.1 but while debugging intellisense still thinks I am in NETFRAMEWORK with respect to checking code in #if directives. How can I tell the dev env I am using core?

**Comment by lie112** [comment] 2021-02-10 23:51
Have you got SimplePropertyPresenter working in core? I can't get SPPresenter to display in my property presenter code and not sure if I am chasing something that's not currently working.

**Comment by hol430** [comment] 2021-02-11 00:04
I believe visual studio should automatically detect which target framework you're debugging and automatically adjust which sections of the code are greyed out. It may sound silly but perhaps double check the condition in the directive - some are `#if NETFRAMEWORK` and some are `#if NETCOREAPP` - could you be looking at the wrong section?. Otherwise I'm not sure why it's not updating for you, as I haven't had any problems like that in my tests with visual studio.

SimplePropertyPresenter does indeed work in the .net core builds. You should see it if you click on a paddock or a soil or a clock.

**Comment by hol430** [comment] 2021-02-11 23:08
- Need to fix the tooltip button (currently it gives an error `No property with name 'gtk-tooltip-timeout' in type 'GtkBox'`)

**Comment by lie112** [comment] 2021-02-12 00:08
The identity of the framework used in Visual studio code is obtained from the <TargetFrameworks>netcoreapp3.1;net472</TargetFrameworks> of the csproj file. The order here seems to matters. Intellisense will assume the first entry. So to see CoreApp3.1 code highlighted it must come first. I haven't found anywhere to se this in the interface.

**Comment by hol430** [comment] 2021-02-12 00:23
Ah, ok I had assumed you were using visual studio. Yeah, this is a problem with the omnisharp project - hopefully it will be fixed one day, but in the meantime I've just been manually editing the csproj (and being careful not to commit the changes). Out of interest, how are you debugging the .net framework builds? I didn't realise it was possible to debug .net framework projects from vscode without using mono

**Comment by lie112** [comment] 2021-02-12 00:25
I am using visual studio 2019. Sorry for confusion in my abbreviations

**Comment by hol430** [comment] 2021-02-14 23:56
- Graph performance is extremely bad when marker type is not set to none

**Comment by hol353** [comment] 2021-03-03 22:35
New property presenter in .net core isn't showing a drop down box for:
```c#
        [Description("Crop")]
        public IPlant Crop { get; set; }
```
![image](https://user-images.githubusercontent.com/1943827/109881752-87e07300-7cc4-11eb-81ac-6b70e8bd9060.png)

Crop should be a dropdown on the properties page

Example of this is in 'Sow on a fixed date' in the management toolbox.

**Comment by hol430** [comment] 2021-03-03 22:50
The current logic is that if no specific display type is specified, and the property is an IModel of some sort, then UI will show a dropdown with all models in scope which are of a type assignable to the property. In this case that's not working because IPlant is not an IModel (if you change your property from IPlant to Plant it will work)l. I realise there are a lot of .apsimx files which use the property this way, but as things stand I don't think we want to allow your use case to work (IPlant is not an IModel, so the concept of scope doesn't apply to IPlant anyway). As it happens, all implementations of IPlant also happen to implement IModel, so I would suggest the best solution may be for IPlant to inherit/implement IModel. Thoughts?

**Comment by hol353** [comment] 2021-03-03 23:08
I'm happy with that but we will need to change the rules in the management toolbox because they don't work out of the box.

**Comment by hol353** [comment] 2021-03-15 22:08
Can't navigate in the report data window. Arrow keys don't work and there is no horizontal scroll bar. There is a vertical one though.

![image](https://user-images.githubusercontent.com/1943827/111227676-a7658d00-862e-11eb-84a5-9527c2581968.png)

**Comment by hol353** [comment] 2021-03-15 22:42
I can't seem to debug manager scripts. If I put 

Debugger.Break();

into a manager script Visual Studio breaks OK but says it hasn't loaded any symbols:
![image](https://user-images.githubusercontent.com/1943827/111230565-89e6f200-8633-11eb-997a-6ef386b52d29.png)

**Comment by zur003** [comment] 2021-03-16 10:36
Re manager script debugging: Currently we're generating the .pdb in memory. It probably needs to be saved to a file for the IDE to access it. It may also require that the source be saved to a file. The solution at https://stackoverflow.com/questions/50649795/how-to-debug-dll-generated-from-roslyn-compilation comes close to working.

It's worth noting that generating a .pdb and streaming it (and source) to a file do take a bit of extra time. Perhaps the Manager should have "Save debugging information" as a user-settable option, so it's there if developers need it, but doesn't slow things down for "normal" users.

**Comment by lie112** [comment] 2021-03-18 04:39
Formatting in Upgrade presenter for GTK# core
- Cannot increase size of window holding available upgrades
- Padding around checkbox to "Display Old Versions"
- Pad info in markdown box ("You are currently using a custom build)
- Do not send "You are currently using a custom build" as error to lower status bar

**Comment by hol353** [comment] 2021-04-08 21:18
Soil download dialog doesn't work in .net core build. This was because of the reliance of SOAP based web apis something that is hard / impossible in .net core. There is a REST api though:

http://apsimdev.apsim.info/ApsoilWebService/Service.asmx/SearchSoilsReturnInfo?latitude=-27&longitude=150&radius=1000&SoilType=

This will give you a list of soils within 1000km of a lat and long. Leaving SoilType to blank will get it to return all soils. Otherwise soils will be filtered by the specified soil type.

**Comment by hol353** [comment] 2021-04-13 02:44
In the GTK3 build a page of graphs has 10 charts on it. I should have 4. Also the event names have a box around them e.g.

![image](https://user-images.githubusercontent.com/1943827/114489138-f9152d80-9c55-11eb-80b7-4ce2d09b7892.png)

**Comment by hol353** [comment] 2021-04-13 02:57
Size of icons in simulation tree are much smaller than the gtk2 version.

**Comment by hol430** [comment] 2021-04-14 01:20
@hol353 the soils returned from the above REST api don't contain the soil profile data such as ll, dul, sat, etc. This is all we get:

```
<SoilInfo>
    <Name>Soils/Australia/Queensland/Darling Downs and Granite Belt/Black Vertosol-Bongeen (Dalby No027)</Name>
    <Description>Clay - Toowoomba - Wheat ll,xf copied from sorghum. Wheat kl is just default apsim kl values for wheat.</Description>
    <SoilType>Clay</SoilType>
    <Latitude>-27.12</Latitude>
    <Longitude>151.305</Longitude>
    <Distance>8.0205653151638749</Distance>
    <ASCOrder>Vertosol</ASCOrder>
    <ASCSubOrder>Black</ASCSubOrder>
    <Site>Dalby</Site>
    <Region>Darling Downs and Granite Belt</Region>
    <NearestTown>Dalby, Q 4405</NearestTown>
</SoilInfo>
```

Is there another endpoint from which we can retrieve the missing info?

**Comment by hol430** [comment] 2021-04-14 01:28
> the event names have a box around them

These boxes appear for me on both gtk2 and gtk3 builds. Do we want to get rid of them anyway?

**Comment by hol430** [comment] 2021-04-14 01:38
> Size of icons in simulation tree are much smaller than the gtk2 version.

My icon sizes are also the same in both gtk2 and gtk3 builds. Can you post a screenshot of the icons that look different on your computer?

![image](https://user-images.githubusercontent.com/36427516/114641571-b450cb80-9d15-11eb-9d81-79faa06f6ba3.png)

**Comment by hol353** [comment] 2021-04-14 02:20
> Is there another endpoint from which we can retrieve the missing info?

https://apsimdev.apsim.info/ApsoilWebService/Service.asmx/SoilXML?Name=Soils/Australia/New%20South%20Wales/Riverina/Sandy%20clay%20loam%20over%20light%20to%20medium%20clay%20(Henty%20No701)
This will give you APSIM soil xml for a soil as per APSIM 7.10 format.

> These boxes appear for me on both gtk2 and gtk3 builds. Do we want to get rid of them anyway?

Yep get rid of the boxes.

> Can you post a screenshot of the icons that look different on your computer?

![image](https://user-images.githubusercontent.com/1943827/114644908-c3d31300-9d1b-11eb-8e49-79b888363605.png)

**Comment by hol430** [comment] 2021-04-20 22:32
@hol353 do you know what sort of display scaling you were using when you took the above screenshot?

**Comment by hol353** [comment] 2021-04-20 22:46
It would have been 150% display scaling.

**Comment by lie112** [comment] 2021-04-28 06:33
It seems CTRL+PgUp and PgDwn doesn't move a model in the tree in Core, but moves focus box up the tree.
Also the tree in ExplorerView could have some space at bottom as it is difficult to work with the last entry when the scroll bar appears over it.

**Comment by zur003** [comment] 2021-04-28 06:50
It appears to do the same under Frameworks, so this isn't really the right issue to describe the problem, but it is rather unexpected behaviour, as it moves the focus box, but not it's highlighting. Use ctrl+ up-arrow or down-arrow to move models.

**Comment by lie112** [comment] 2021-04-28 23:23
I think the problem arose because I must have accidently double clicked to go into name edit mode and then hit up arrow to return to selected mode. In this state crtl + up arrow doesn't work. I was also struggling to get control of the model partly hidden by the bottom horizontal scrollbar and could only use keyboard shortcuts, so that incorrectly led me down the path of thinking it must be ctrl + page up to move the model. 
Is there a way to reassign a comment and related posts to a new issue? Is that the "reference in new issue" option?

**Comment by hol430** [comment] 2021-06-07 23:54
XYPairs presenter doesn't work properly in .net core. It scrolls down after typing text into a cell. It also shows many empty cells beneath the populated cells.

**Comment by hol430** [comment] 2021-09-13 02:38
Closing this issue as it's quite vague. We will create separate issues for any individual bugs we run across in the gtk3 version.

**Closed by hol430** 2021-09-13 02:38 UTC
Labels: bug, interface/infrastructure
