### ISSUE TITLE
"System.NullReferenceException: Object reference not set to an instance of an object" error report in morris analysis

### ISSUE THREAD

**Issue by yangxuening** [APSIMInitiative/ApsimX#7984] opened 2023-05-15 11:15 UTC
### What happened?

Hi, all
I'm doing the global sensitivity analysis (morris) of ApsimX-Maize model. I have run the morris examples named _[Sensitivity_MorrisMethod.apsimx]([ApsimXfiles.zip](https://github.com/APSIMInitiative/ApsimX/files/11477139/ApsimXfiles.zip))_ successfully. However, there are some error reports after changing parameters based on the morris examples.
The error reports are as follows:

### 

System.Exception: Error in file: D:\ApsimXfiles\Morris_v1.apsimx Simulation: MorrisMethodExampleSimulation6
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.DataTable.SerializeDataTable(SerializationInfo info, StreamingContext context, Boolean isSingleTable, SerializationFormat remotingFormat)
   at System.Data.DataTable.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, BinaryFormatterWriter serWriter)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at APSIM.Shared.Utilities.ReflectionUtilities.BinarySerialise(Object source, SerializationBinder binder) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 328
   at APSIM.Shared.Utilities.ReflectionUtilities.Clone(Object sourceObj) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\Utilities\ReflectionUtilities.cs:line 561
   at Models.Core.Apsim.Clone[T](T model) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Apsim.cs:line 76
   at Models.Core.Run.SimulationDescription.ToSimulation() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 156
   --- End of inner exception stack trace ---
   at Models.Core.Run.SimulationDescription.ToSimulation() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 188
   at Models.Core.Run.SimulationDescription.Prepare() in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\Models\Core\Run\SimulationDescription.cs:line 104
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\JobRunning\JobRunner.cs:line 213

And sometimes the Report and DataStore report nothing.

Could you help me to check it? Thanks!

[ApsimXfiles.zip](https://github.com/APSIMInitiative/ApsimX/files/11477143/ApsimXfiles.zip)

### What Operating System are you on?

Windows

**Comment by par456** [comment] 2023-06-05 23:10
Sorry for the delay on looking at this.

I was not able to reproduce the crash you had, the sim you sent ran all the way through. Was there specific parameters you changed that caused the crash?

About why you weren't seeing any results, the report frequency list was empty on the report node, which means it would never generate any report data.
![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/7205c248-ecad-495a-a8c7-e0257fe47754)


Putting an event into here like [Clock].EndOfDay and it filled up the datastore no problems.
![image](https://github.com/APSIMInitiative/ApsimX/assets/130029141/a2f68770-95ec-4cf9-9431-f7f828edd0f6)

**Comment by par456** [comment] 2023-07-06 03:55
Closing Issue. Reply with a comment if it needs to be reopened.

**Closed by par456** 2023-07-06 03:55 UTC
Labels: bug
