### ISSUE TITLE
lists in filter

### ISSUE THREAD

**Issue by MarkLieffering** [APSIMInitiative/ApsimX#5642] opened 2020-09-07 02:16 UTC
Screenshot is of a DataStore filter. Note how the values for the line "List columns to include (csv). Leave empty for all columns" runs off the screen. Is it possible to make this a vertical list (i.e. going down by rows) to improve readability?

Cheers

![image](https://user-images.githubusercontent.com/32279744/92342254-66873b80-f114-11ea-8a9f-85cd23ee41a9.png)

**Comment by MarkLieffering** [comment] 2020-09-08 21:26
@hol430 - just a follow on from this filter issue - is there a reason that outputs using square brackets as in [AGPRyegrass].AboveGroundLiveWt are not in the filtered datastore? The are only filtered if they are renamed in the report. Here are some screenshots to hopefully illustrate this issue:

the report properties:

![image](https://user-images.githubusercontent.com/32279744/92528711-52ab1900-f27d-11ea-8755-6298bf32752f.png)

the report data:

![image](https://user-images.githubusercontent.com/32279744/92529275-53907a80-f27e-11ea-8081-bc84cf1352ae.png)

the filter:

![image](https://user-images.githubusercontent.com/32279744/92529366-7de23800-f27e-11ea-9719-c738ef08d9e9.png)

the datastore  - only the outputs that have been renamed are filtered (note numbers are different than the report because of the filtering):

![image](https://user-images.githubusercontent.com/32279744/92528961-d402ab80-f27d-11ea-92b6-309928d8421b.png)

**Comment by hol353** [comment] 2020-09-09 21:22
@MarkLieffering  I've fixed the bug you identify in the 2nd comment above.

@hol430 : Re first comment above: it would be good to have a multi-line option in the filter (and PropertyPresenter in general). After looking at the grid control we use, I think this will be difficult. Perhaps we need to rethink the PropertyPresenter (i.e. don't use a grid but instead some sort of Flow Layout with normal controls) or find another grid control (or write one ourselves).

**Comment by hol430** [comment] 2020-09-09 23:15
Yeah the standard input mechanism for arrays is comma-separated values. It works well for short arrays but not for long ones. I agree that if we want this feature, we might have to think about moving away from a grid (GtkTreeView) layout for the property presenter. We could instead just generate a form on the fly (from code) using a combination of labels and Entry/CheckButton/whatever widgets for input. This would be more consistent with other software packages but I'm still not sure what would be the best mechanism for an array input though - maybe something like this would work?

![image](https://i.stack.imgur.com/SDDAs.png)

**Comment by hol353** [comment] 2020-09-09 23:30
Or just a multi-line edit box where each line is another element of the array.

**Comment by hol430** [comment] 2020-09-10 23:47
Yeah that would be a good option too. In some situations though it might be better to show the values on one line, separated by commas. E.g. the excel input component. I'm really looking forward to moving away from the grid view for the property presenter, it will make some things a lot easier. The only problem I see is that the GtkTable widget is deprecated in gtk3 in favour of GtkGrid (which basically does the same thing but the API looks a bit different). So our code would need to be different when targeting gtk2 vs gtk3.

**Comment by hol430** [comment] 2021-01-05 05:46
@hol353 - the initial feature request from this issue (a multi line text input) has been implemented for the new property UI, so changing the UI for the filter component is a 1-line change now. However, there's no multi-line text input for the old property presenter/gridview which still uses comma-separated values in a single cell. The problem is the tooltip, which currently specifies comma-separated values - this will be incorrect if the user is using the new property presenter, and there's no way to change the tooltip based on which property presenter is being used. I think the time has come to replace the old property presenter altogether, as I've been using the new one for months without issue. Let me know what you think.

**Comment by hol353** [comment] 2021-01-22 02:16
Yep I agree. Lets go with the new property presenter. Much nicer!

**Closed** 2022-01-31 23:37 UTC
Labels: interface/infrastructure
