### ISSUE TITLE
Figure when factor only has one level

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3189] opened 2018-10-22 03:54 UTC
The figure cannot be shown when there is one level in the factor. 

1: One factor with one level
![image](https://user-images.githubusercontent.com/1657381/47277250-846f5400-d601-11e8-9418-6ada0603b949.png)

2: Multiple factors with one level

![image](https://user-images.githubusercontent.com/1657381/47277209-162a9180-d601-11e8-937d-4d67d1f4fdee.png)

Attached an example apsimx file: [factors.zip](https://github.com/APSIMInitiative/ApsimX/files/2500121/factors.zip)

**Comment by hol430** [comment] 2019-02-22 05:24
This seems to be working ok now if my understanding of the problem is correct. All three graphs display data, although only the first one shows multiple colours since it is the only experiment with more than 1 cultivar.

**Comment by hol430** [comment] 2019-12-11 02:27
I'm going to close this. All the graphs in this file appear to work ok for me now. The whole factorial system has been rewritten since this issue was created so I'm not surprised the bug has been fixed.

**Closed by hol430** 2019-12-11 02:27 UTC
Labels: bug, interface/infrastructure
