### ISSUE TITLE
Problem with incomplete initialisation not being detected

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#7288] opened 2022-05-18 00:08 UTC
I've recently noticed problems with the data store, but haven't worked out exactly what is going wrong. As an example, I just updated my installed version of ApsimX and ran an old wheat simulation. The simulation appeared to run normally, but at the conclusion there was nothing in the data store other than the initial conditions. Other outputs were apparently either not stored, or were wiped away at the end of the run. Running the same simulation a second time provided normal results. I've sometimes noticed a similar problem when moving between the installed version and my locallly compiled version - the run appears to execute normally, but the data store holds nothing beyond initialisation values.

**Comment by zur003** [comment] 2022-05-18 03:47
Further diagnosis - the problem isn't with the datastore, but rather with event handling. I can reproduce the problem by running a copy of the Wheat example under my installed version, then attempting to re-run using my locally compiled version in the IDE. The only simulation events configured to go to the report are [Wheat].Harvesting events, but these events are apparently not being handled. Oddly, just setting a breakpoint in the EventReportFrequency constructor causes the problem to disappear, so it sounds like it might be a threading/timing issue of some sort. But it only seems to be a problem the first time the simulation is run. Very strange....

**Comment by zur003** [comment] 2022-05-18 04:40
Yet another update - after being able to reproduce the problem fairly reliably, it now seems to have disappeared after deleting the .db file. So there may have been some problem with the database, but I'm still mystified as to exactly what happened. Has anyone seen a similar problem? If not, I'm willing to close this issue, though I'd like to understand exactly what happened. (By the way, the obervation about the breakpoint in EventReportFrequency probably wasn't correct.)

**Comment by lie112** [comment] 2022-05-18 04:49
I have seen some odd outcomes from reported data over time, but never been able to reproduce them. I find that I often delete the database rather than "empty datastore" to clean things up and start afresh. I often wondered if the clear datastore should delete the db file rather than empty the tables especially if the new runs want to get rid of old unused column names. I have sometimes found the _Messages table is not cleared and you can end up with old messages reported and spend a lot of time trying to fix them only to realise they are not present if the database is deleted (I think this may have been addressed in recent fixes to Summarise). This may relate to needing to better empty the database of errors when opening a new simulation tab as a json based error from last unsuccessful opening will still be displayed, but this is not a database issue, but a clear display issue.

**Comment by zur003** [comment] 2022-05-18 11:10
It appears I've been chasing a lot of false leads. The problem is actually with model initialization. What I was doing was loading a model, then immediately pressing the Run button. InitialiseModel runs on a background thread when the file is read, and I was initiating the run before model initialisation was complete. This was then resulting in the manager scripts not loading correctly, so sowing and harvesting were not occurring.
This scenario is probably not that common; the gap between opening the file and pressing Run needs to be quite short, but it can happen. Any suggestions for how to correct this? Could we put a flag in InitialiseModel that is set when initialisation is complete, and only start a run when that flag has been set?

**Comment by lie112** [comment] 2022-07-04 00:01
I am able to add a little more light on this, but unable to understand the timing of what appears threaded (mentioned in code comments) writing to database.

After the startofsimulation event CLEM has two initialisation events (Resources and Activities) and a validation event before the FinalInitialise and start of daily loop of events. During initialisation and validation a number of errrors and warnings are written to summary _Messages, then after all my validation in CLEMValidate I check these warnings and errors and throw an error and stop if problems are detected.

However, when running a brand new simulation with no .db file previously created when I check _Messages for errors they are not there and the table is empty even though I can break and step through the writing of the error as it happens so I know it should be there.  The .db file is created in this process.

If however, we can run the simulation with the .db file present, then the code runs as expected and the validation errors are detected and an error is thrown in the lower status bar as expected. 

This bug is an issue as a user is not informed of any validation errors if no db file is present. I believe this is linked to what I had seen previously where prior errors sometimes displayed after being addressed so it's hard to work out just where you are. Now deleting the db file is not the solution.

So it would appear the ability to interogate the _Messages table is not possible until Post Tools after the simulation has completed when the simulation had to create the table. l couldn't identify where the table was created  and maybe it's in FinalInitialise after I need it. However, no error is thrown as we use Summary.Write to write the intended warnings and errors.

You can reproduce this in a CLEM example simulation, but setting the start date to be after the end date which CLEM will validate, with and without the db file present.

**Closed** 2022-10-20 21:02 UTC
Labels: bug, interface/infrastructure
