### ISSUE TITLE
@peter-devoil and/or @jwhish?

### ISSUE THREAD

**Issue by masooandy** [APSIMInitiative/ApsimX#5786] opened 2020-10-24 16:57 UTC
@peter-devoil and/or @jwhish?

_Originally posted by @sarahcleary in https://github.com/APSIMInitiative/ApsimX/issues/5120#issuecomment-633764322_

**Comment by masooandy** [comment] 2020-10-24 17:01
Hi folks 
Could you help me finding  chicory cultivar coefficients or any other plants in apsimx?
Kindly regards

**Comment by masooandy** [comment] 2020-10-24 17:05
Hi folks 
Could you help me finding  chicory cultivar coefficients or any other plants in apsimx?
Kindly regards

**Comment by BrianCollinss** [comment] 2020-10-25 08:32
@masooandy it'd be good to follow the forum convention for the title of the posts/issues so everyone would know what it is about without reading them. Cheers.

**Comment by masooandy** [comment] 2020-10-25 10:54
@BrianCollinss you can found it here https://github.com/APSIMInitiative/ApsimX/issues/5758 eventhough I'v got no response yet.

**Comment by BrianCollinss** [comment] 2020-10-25 11:00
I don't think creating a second issue will help.

**Comment by hol430** [comment] 2020-10-25 23:46
Duplicate of #5758.

**Closed by hol430** 2020-10-25 23:46 UTC
Labels: question
