### ISSUE TITLE
'Automatic irrigation based on water deficit' in Management Toolbox doesn't work as intended

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3373] opened 2018-12-09 22:58 UTC
I am looking into the 'Automatic irrigation based on water deficit' in the Management Toolbox, where I first saw the **MathUtilities.Sum**. There are two functions here that seem strange:
- First, **GetLayerIndex** returns the index of the previous layer if the target depth (FASWDepth) is within the current layer. 
- Then, **MathUtilities.Sum** (that ignores the last layer) is used to calculate avail_sw and pot_avail_sw. It means that two last layers are ignored here. 

I still think it is a good idea to change **MathUtilities.Sum** so it accounts for the last value (i.e. index). It's strange that each time the user needs to add +1 to the lastIndex to make sure the function takes the last value into account while summing. The function is only used 3-4 times in the code so it can be changed quickly. 

Please see: 
https://github.com/APSIMInitiative/APSIM.Shared/issues/71
https://github.com/APSIMInitiative/APSIM.Shared/pull/72

 Example:
- If soil layers are 100mm each. 
- If **FASWDepth** is 250 mm, it falls in the third layer (i=2).
- As FASWDepth < cumThickness[2], **GetLayerIndex** returns i = nlayr = 1.
- Then **MathUtilities.Sum** calculates the avail_sw upto layer i=0.

**Comment by hol430** [comment] 2019-02-06 05:34
Is this a duplicate of #3372?

**Comment by BenAbabaei** [comment] 2019-02-06 05:39
The other one was closed till guys reopened it. The same problem though. I modified Sum function in Apsim Shared. But Dean rejected my suggestion so I closed the pull request. You can find it. Cheers.

**Comment by hol430** [comment] 2019-02-06 05:45
Makes sense - I'll close this one then. No need to have two issues for the same problem.

**Closed by hol430** 2019-02-06 05:45 UTC
Labels: bug, interface/infrastructure
