### ISSUE TITLE
APSIM importer misses NO3 and NH4 fields for InitialNitrogen

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#6340] opened 2021-04-12 23:34 UTC
When using the importer there are two fields missed in the import.

![image](https://user-images.githubusercontent.com/11879671/114475300-5354c500-9c3b-11eb-91f9-d8370e1083b8.png)

**Comment by hol430** [comment] 2021-04-14 23:05
@her123 could these fields have been imported into the chemical node instead of the initial node?

**Comment by her123** [comment] 2021-04-15 04:17
It looks like that may be the case. However they are in different units and the InitialNitrogen component still has the SW column filled. How can I be sure that the simulation won't use the blanks in initial nitrogen as zeros? Also. If I do a reset (SoilNitrogen.Reset()) of the nitrogen will it use the values in Chemical or InitialNitrogen?

**Comment by hol430** [comment] 2021-04-21 01:44
When the simulation is run, a new sample is created to hold the initial conditions. This uses any values in any existing samples as well as the no3/nh4 values in the chemical node. When you do a reset it will use the values in this initial conditions sample. With regards to the incorrect units when importing - can you upload the .apsim file showing the problem? Or is it the yeelanna files you uploaded in #6357?

**Comment by her123** [comment] 2021-04-22 00:23
The two simulations attached show the issues. The Breeza one imports with the N values in layer 1 different to expected.
The Canowindra simulation imports the InitialNitrogen N values into a Chemical component under different units (not reassuring). The new InitialNitrogen component has no initial N values. I don't think this is a nice way to have it.

[sims_import.zip](https://github.com/APSIMInitiative/ApsimX/files/6354609/sims_import.zip)

**Comment by hol430** [comment] 2021-06-16 05:16
In the breeza simulation, the values have been changed because the layer structure in the chemical (analysis) node is different to that in the sample. When the values were moved from the sample to the chemical node, they had to be remapped to the new layer structure.

The canowindra simulation has had the values converted from kgha to ppm - new apsim always stores these values in ppm so this isn't really avoidable. On the plus side, it seems to have got the conversion right.

Moving the initial N from the sample into chemical occurred in one of the converter functions (version 60). This is kind of related to #6505 - I'm not sure what would be best here.

**Comment by hol430** [comment] 2022-01-31 22:48
I'm going to close this as the importer is actually working as intended. #6505 captures some of the confusing aspects of the initial N configuration.

**Closed by hol430** 2022-01-31 22:48 UTC
Labels: bug
