### ISSUE TITLE
Plant.lai incorrectly assumes leaf organ

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#6613] opened 2021-07-06 01:03 UTC
While reporting pinus.lai throws an exception - Line 203 in Plant.cs

**Comment by hol430** [comment] 2021-07-06 01:40
I just tried this on latest master branch, I added `[Pinus].LAI` to the report, and the simulation runs without errors. Are you talking about exceptions which are being thrown but handled internally (so they don't show up in gui)?

**Comment by hol353** [comment] 2021-07-06 02:53
I was with Val virtually when we got this error. The code I saw definately had a problem. I've now looked in the tip revision in GIT and the code is completely different. @sno036 can you do a pull and see if the problem goes away.

**Comment by sno036** [comment] 2021-07-06 02:55
I can but I've already told it to ignore so it won't help much. I was on "7abcd57 - Merge pull request #5846 from sme016/Eucalyptus" from 9:18 (NZ? AU?) this morning.

**Comment by hol430** [comment] 2021-11-03 00:13
I still can't reproduce this one. The code on 7abcd57 for getting LAI from plant is the same on the current master branch. It checks if there is a Leaf organ -> if so, return its LAI, otherwise check for simple leaf, otherwise check for perennial leaf. Pinus uses perennial leaf so this should be fine. Do you guys remember any details about this problem?

**Comment by hol430** [comment] 2022-01-31 23:29
I'm going to close this one as I can't reproduce and the code that I can see should work with pinus in theory. (And in practice it does seem to work.) Feel free to reopen if this is still happening to you.

**Closed by hol430** 2022-01-31 23:29 UTC
Labels: bug, science
