### ISSUE TITLE
error in soil module

### ISSUE THREAD

**Issue by samarambar** [APSIMInitiative/ApsimX#7525] opened 2022-09-26 22:50 UTC
I have been having an issue with the soil model after all versions APSIMX  #2022.9.**7080** to #2022.9.**7088**

I am working on a sugarcane simulation.
I have all values in the soil module changing to very high numbers (with so many "zeros") after I open the soil module the first time.

Figure 1. When I open the soil module for the first time
![Imagem2](https://user-images.githubusercontent.com/66262573/192393182-2863b644-9d9e-429e-b5c5-df0dac9cc8e6.png)

Figure 2. After I open the soil module a second time (just click again):
![Imagem3](https://user-images.githubusercontent.com/66262573/192393199-6e2d9b74-91a9-4fb8-9254-cb0ddd3679c1.png)

And additionally, when I copy and paste the soil module between different APSIMX files the same issue occurs.
I tried many things, like using the soil module of the sugarcane example file (and other crop simulations example files),  but I couldn't fix them.

I tried the 2022.9.7083 (issue in the soil file), but the same issue happen.

Thank you in advance if someone could help me.

**Comment by MarkLieffering** [comment] 2022-09-27 20:40
Some of these issues seem to be similar to https://github.com/APSIMInitiative/ApsimX/issues/7425 which were fixed. As I use the latest and greatest version I am not sure if the issues in 7425 have been picked up by the version you are using. About those really high numbers - I notice that you are using a comma as decimal marker - I seem to remember a couple of years ago there was an issue with that?

**Comment by hol353** [comment] 2023-02-15 00:53
I can't reproduce this. Perhaps it has been fixed. Closing the issue. Please reopen if it is still a problem.

**Closed by hol353** 2023-02-15 00:53 UTC
Labels: bug, interface/infrastructure
