### ISSUE TITLE
Why is Apsim so slow?

### ISSUE THREAD

**Issue by zur003** [APSIMInitiative/ApsimX#4131] opened 2019-08-22 02:37 UTC
It seems that Apsim has recently gotten a bit slower, especially if run under Mono. Running Examples\Wheat on a Linux system here is taking a full minute. Since within-job progress monitoring is currently broken, it's a rather long wait for the user to be sure that anything at all is happening.

**Comment by femiguez** [comment] 2019-09-25 13:32
I can confirm this. On my Mac for build 4035 the wheat example takes 38 seconds and for build 4200 it takes 58.

**Comment by hol430** [comment] 2019-12-09 23:10
Posting this here so I don't forget. Related to this is the long pause after running simulations where the progress bar sits on 100% for a long time. I did some profiling a few weeks ago and it looks like apsim spends a huge amount of time deleting old data from the database. Whenever we write a table, we delete the old rows (from last time we ran the simulation) and this seems to be quite slow. This is most noticeable when there is a PredictedObserved model present.

**Comment by zur003** [comment] 2019-12-13 01:21
I can take some of the blame for this. A while back, I added a "VACUUM" SQLite operation that occurs whenever a table is dropped from the database. Although this tidies things up nicely, it's a slow operation since it actually makes a clean copy of the entire database. 
I think the occasional VACUUM cleanup makes sense, but perhaps it should be done at some other time, rather than whenever any table is dropped.

**Comment by hol430** [comment] 2020-06-17 02:09
I'm going to close this, as the original issues here have been resolved, and the issue is quite general. New issues can be opened for any new performance regressions.

**Closed by hol430** 2020-06-17 02:09 UTC
Labels: interface/infrastructure, refactor
