### ISSUE TITLE
GTK interface-not showing up new objects

### ISSUE THREAD

**Issue by Xiumei2017** [APSIMInitiative/ApsimX#1903] opened 2017-08-22 23:42 UTC
If you try to copy and paste a new objects, it won't show up until you reopen the interface again.

**Comment by zur003** [comment] 2017-08-23 00:14
This may be a duplicate of #1777.

I have not been able to reproduce this problem. Can you provide an example giving the exact steps that produce the problem?

**Comment by Xiumei2017** [comment] 2017-08-23 01:21
If I try to add a model to the plant level in replacement, I right click and select add model, then copy or drug or click "add", it won't show up until I reopen the interface.

**Comment by zur003** [comment] 2017-08-23 01:36
The newly added node always shows up right away for me. Does this happen for you consistently?

@hut104 - you reported something similar (#1777). Is this problem readily reproducible for you?

**Comment by HamishBrownPFR** [comment] 2017-08-23 01:42
HI @zur003 
I have been seeing this problem alot with people using the GTK interface.  If you try to add an object using the add opton on the context menu, or by copy and paste or by drag and drop it does not show up until you reopen the GUI.  It is intermittent and seems to work better when the GUI is freshly opened.

**Comment by hut104** [comment] 2017-08-23 02:00
Agreed. Same for me. Sporadic. But I resolve the issue the same way.

Sent with AquaMail for Android
http://www.aqua-mail.com

On 23 August 2017 11:43:05 Hamish Brown <notifications@github.com> wrote:

HI @zur003<https://github.com/zur003>
I have been seeing this problem alot with people using the GTK interface. If you try to add an object using the add opton on the context menu, or by copy and paste or by drag and drop it does not show up until you reopen the GUI. It is intermittent and seems to work better when the GUI is freshly opened.

-

**Comment by zur003** [comment] 2017-08-23 02:21
Ugh. It's not easy to fix a problem that doesn't appear consistently. I'll need help with this, since I've never been able to reproduce the problem myself, and I don't see any likely points of failure in the source code. Here are a few observations that you might make that could help isolate the problem:

1) Once this problem appears, does it then happen consistently from then on? That is, once a pasted node fails to appear, do ALL subsequent attempts to insert nodes fail to display?

2) If failures do happen more than once in a session, is it happening everywhere in the tree, or only on certain branches?

3) If only on certain branches, how and when were those branches created?

4) When "add" operations fail to display correctly, do attempts to move nodes up and down (either by the popup menu, or by Control-up/ Control-down) also fail to update the display?

5) Does deleting a node also fail to display as expected?

**Comment by rcichota** [comment] 2017-08-23 04:28
I've noticed the same issue too, and not only in GTK, the 'normal' (windows) interface also has this issue.
From my experience, it occurs after a simulation runs, once it happens it consistently happens. Only solution is to close and re-open. This definitely happens when working using 'Replacements', but I think it does also in the simulation items (e.g. graphs)...

**Comment by zur003** [comment] 2017-08-23 05:12
Ah! Thanks, Rogerio. I've now been able to replicate the problem. Looks like it may be an issue with parents of objects not being reset correctly at the conclusion of a run with Replacements. At least now I know where to start looking.

**Closed** 2017-08-23 22:05 UTC
