### ISSUE TITLE
Profiling and refactoring needed to increase execution speed

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3509] opened 2019-02-13 04:32 UTC
Profiling and refactoring may assist in increasing execution time.

**Comment by hol353** [comment] 2020-07-27 00:17
Nutrient is very slow. Almost 30% of run time is in calculating carbon and nitrogen flows:
![image](https://user-images.githubusercontent.com/1943827/88493035-51d26680-cff2-11ea-8ee5-f1fb2d3c7bd9.png)

**Comment by hut104** [comment] 2020-07-27 04:09
Could approach this in a similar manner to previous speed-up work in Nutrient - develop functions that encapsulate a particular approach for N flows.

**Comment by hol353** [comment] 2020-07-29 00:03
Some timings using 100 year wheat example.

APSIM Classic: 41 sec
APSIM Next Gen with nutrient: 11.5 sec  (3.5 times quicker than classic)
APSIM Next Gen with soil nitrogen: 7.5 sec (5.5 times quicker than classic)

**Comment by hol430** [comment] 2020-07-29 00:10
Is this after your changes? The wheat example normally takes around 40 seconds for me on my laptop.

**Comment by hut104** [comment] 2020-07-29 06:40
Dean, Try these again with the latest changes in the "Wheat" pull request currently on jenkins.

________________________________

**Comment by hol353** [comment] 2020-07-29 21:17
Good job Neil. New timings:

APSIM Next Gen with nutrient: **8 sec**

NFlow is now well down the list of slow methods. Now 27% of runtime is spent in CarbonFlow:

![image](https://user-images.githubusercontent.com/1943827/88854450-a2390680-d234-11ea-9ed9-bf53418900ff.png)

**Comment by hol353** [comment] 2020-07-31 03:32
Run time is largely unchanged at around the 8sec mark:
![image](https://user-images.githubusercontent.com/1943827/88997100-38068b80-d332-11ea-9afc-b7e91ce54ccb.png)

**Comment by hut104** [comment] 2020-07-31 06:09
Those two lines are now insignificant components of overall execution time.  I'll now try the other bottlenecks.

**Comment by hol353** [comment] 2020-08-02 23:31
No real difference. Maybe slightly quicker. I think you're being beaten by the fact that these functions are called inside of soil layer for loops. The hit counts are very high.

![image](https://user-images.githubusercontent.com/1943827/89134850-c7e34a00-d56b-11ea-8dad-531153ceb392.png)

**Comment by hol430** [comment] 2020-08-02 23:34
How much speed do you gain if you remove the 'read tomorrow's met data' hack which causes an exception to be thrown at the end of most simulations?

**Comment by hol353** [comment] 2020-08-03 21:20
Runtime now 7.9sec
![image](https://user-images.githubusercontent.com/1943827/89228387-de98a800-d622-11ea-9aee-c5e912f1595e.png)

**Comment by hol353** [comment] 2020-08-04 21:28
Runtime now 4.5 sec. Making real progress!

![image](https://user-images.githubusercontent.com/1943827/89346934-3996d180-d6ed-11ea-865c-e3dfa244eb66.png)

**Comment by jbrider** [comment] 2020-08-04 22:09
Great work! Is that using the 3rd party product still (I forget the name of it).

**Comment by hol430** [comment] 2020-08-04 22:21
The exception I mentioned above usually only happens once per simulation, I expect it would have a much bigger impact on multi-simulation runs. When you say you've removed it, do you mean you've removed it on your local copy? The problem is still there on master branch.

**Comment by hol353** [comment] 2020-08-05 00:20
@ hol430 : I mean i temporarily stopped the exception from happening in this sim by putting in a hack. It is not part of the PR (I hope)
@jbrider: I'm using the ANTS performance profiler by RedGate. It is a great tool.

**Comment by hol430** [comment] 2020-08-05 23:27
@hol353 the LUDF simulation in the stock test set takes a good minute to run on my pc. That is with a debugger attached but it seems like quite a long time for a 13 year simulation (compared to continuous wheat). If you are starting to hit diminishing returns with the wheat example, maybe it's worth looking into.

On a related note, jenkins builds are run in debug mode. We could probably speed them up quite a bit just by building in release mode, although you probably wouldn't get line numbers in stack traces as a result. What do you think would be better?

**Comment by hut104** [comment] 2020-08-05 23:55
Some of the changes have been made to wheat.json.  These would need to be inserted into other crop models to speed them up as well. Not sure that can be automated.

**Comment by hol353** [comment] 2020-08-06 01:23
I thought Jenkins was in release mode. I think you do get line numbers in release model. You can certainly debug APSIM when it has been built in release mode. Try changing Jenkins to release mode and see what happens.

**Comment by hol353** [comment] 2020-08-07 01:52
**Current timings:**

**Wheat example**

APSIM 7.10: 41 sec
APSIM Next Gen prior to profiling: 11.5 sec
APSIM Next Gen after profiling: 4.8 sec

**AgPasture timings using Winchmore 1966 Dryland (from validation):**

APSIM 7.10: 120 sec
APSIM Next Gen prior to profiling: 14.5 sec
APSIM Next Gen after profiling: 10.7 sec

**Comment by hut104** [comment] 2020-08-07 23:49
So how much time is now in CalculateRootActivityValues?
It iterates through layers and then iterates through all layers for each layer multiple times.  Each iterator accesses Soil.thickness multiple times.  We'd found this to be costly in other areas.

        /// <summary>
        /// Calculate Root Activity Values for water and nitrogen
        /// </summary>
        public double[] CalculateRootActivityValues()
        {
            double[] thickness = soil.Thickness; // use local for efficiency reasons

            double[] RAw = new double[thickness.Length];
            for (int layer = 0; layer < thickness.Length; layer++)
            {
                if (layer <= soil.LayerIndexOfDepth(Depth))
                    if (LayerLive[layer].Wt > 0)
                    {
                        RAw[layer] = -WaterUptake[layer] / LayerLive[layer].Wt
                                   * thickness[layer]
                                   * soil.ProportionThroughLayer(layer, Depth);
                        RAw[layer] = Math.Max(RAw[layer], 1e-20);  // Make sure small numbers to avoid lack of info for partitioning
                    }
                    else if (layer > 0)
                        RAw[layer] = RAw[layer - 1];
                    else
                        RAw[layer] = 0;
            }
            return RAw;
        }

        /// <summary>Calculates the layer index for a specified depth.</summary>
        /// <param name="depth">The depth to search for.</param>
        /// <returns>The layer index or throws on error.</returns>
        public int LayerIndexOfDepth(double depth)
        {
            double CumDepth = 0;
            double[] thickness = Thickness; // use local for efficiency reasons
            for (int i = 0; i < thickness.Length; i++)
            {
                CumDepth = CumDepth + thickness[i];
                if (CumDepth >= depth) { return i; }
            }
            throw new Exception("Depth deeper than bottom of soil profile");
        }

        /// <summary>Returns the proportion that 'depth' is through the layer.</summary>
        /// <param name="layerIndex">The layer index</param>
        /// <param name="depth">The depth</param>
        public double ProportionThroughLayer(int layerIndex, double depth)
        {
            double depth_to_layer_bottom = 0;   // depth to bottom of layer (mm)
            for (int i = 0; i <= layerIndex; i++)
                depth_to_layer_bottom += Thickness[i];

            double depth_to_layer_top = depth_to_layer_bottom - Thickness[layerIndex];
            double depth_to_root = Math.Min(depth_to_layer_bottom, depth);
            double depth_of_root_in_layer = Math.Max(0.0, depth_to_root - depth_to_layer_top);

            return depth_of_root_in_layer / Thickness[layerIndex];
        }

**Comment by hol353** [comment] 2020-08-09 21:49
Wheat APSIM Next Gen after profiling: 4.4 sec

![image](https://user-images.githubusercontent.com/1943827/89742501-eb634300-dadd-11ea-8fae-a818743b1869.png)

**Comment by hut104** [comment] 2020-08-09 23:37
???? That seems better than I’d thought. I guess we maintain the rage if we are still getting 5-10% reductions in execution time.

**Comment by hol430** [comment] 2021-01-29 05:02
Need to explore some mechanism to convert a PMF model into C# code which doesn't use reflection.

**Comment by hol430** [comment] 2021-08-04 00:16
Closing as too vague.

**Closed by hol430** 2021-08-04 00:16 UTC
Labels: refactor
