### ISSUE TITLE
Issue in the soil file 

### ISSUE THREAD

**Issue by Jatinderbai** [APSIMInitiative/ApsimX#7435] opened 2022-08-10 11:27 UTC
The soil files that already created in the APSIM are not editable, i tried to delete some of the profile but not able to do so, please add a layer deleting option along with copy paste

**Comment by Jatinderbai** [comment] 2022-08-10 18:11
Add a option to Create a new model in the soil file to give blank file, so that one can create new file according to the requieement

**Comment by zur003** [comment] 2022-08-11 00:15
This is largely a duplicate of #7392.

**Closed** 2022-09-02 02:37 UTC
Labels: bug, interface/infrastructure
