### ISSUE TITLE
Error when reporting CERES Denitrification factors

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#5746] opened 2020-10-15 23:17 UTC
A 'invalid report variables' error produced (see below) when reporting:
[Soil].Nutrient.NO3.Denitrification.Rate.CERESDenitrificationTemperatureFactor
[Soil].Nutrient.NO3.Denitrification.Rate.CERESDenitrificationWaterFactor

System.Exception: ERROR in file: C:\OneDrive - CSIRO\Apswork\Denitrification\HenrikeMielenzSites\Horsham\APSIMNextGen\2007\Nutrient_Test\Nutrient.apsimx
Simulation name: HorshamTreatmentN50Irr
System.Exception: Error in report DenitReport: Invalid report variables found:
Soil.Nutrient.NO3.Denitrification.Rate.CERESDenitrificationTemperatureFactor: Layer number must be provided to CERES Denitrification Temperature Factor
Soil.Nutrient.NO3.Denitrification.Rate.CERESDenitrificationWaterFactor: Layer number must be provided to CERES Nitrification Model
   at Models.Report.DoOutput()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken) ---> System.Exception: Error in report DenitReport: Invalid report variables found:
Soil.Nutrient.NO3.Denitrification.Rate.CERESDenitrificationTemperatureFactor: Layer number must be provided to CERES Denitrification Temperature Factor
Soil.Nutrient.NO3.Denitrification.Rate.CERESDenitrificationWaterFactor: Layer number must be provided to CERES Nitrification Model
   at Models.Report.DoOutput()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Models.Clock.OnDoCommence(Object sender, CommenceArgs e)
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   --- End of inner exception stack trace ---
   at Models.Core.Simulation.Run(CancellationTokenSource cancelToken)
   at APSIM.Shared.JobRunning.JobRunner.RunActualJob(IRunnable job, IJobManager jobManager)

**Comment by hol430** [comment] 2020-10-16 01:44
Looks like these components weren't really designed with reporting in mind. The problem is you need to specify a soil layer to return. As a temporary measure you should be able to use `[Nutrient].NO3.Denitrification.Rate.CERESDenitrificationTemperatureFactor.Value(0)` in your report. (Substitute 0 with the layer you're interested in.) If no one has objections, I'll add a `double[]` property to this component so you can report the entire array, slices or individual elements (and the property will show up in the intellisense).

**Comment by hol430** [comment] 2020-10-16 03:00
Ok you should now be able to use this syntax:

```
[Nutrient].NO3.Denitrification.Rate.CERESDenitrificationTemperatureFactor.Values
```

Note that the Values property is an array so the different ways of accessing array properties should also work (see report docs on the website).

**Comment by hol430** [comment] 2020-10-21 23:42
@JodyBig - I'm going to close this as the original problem has been fixed. As per above comment, you should be able to get the denitrification factors via something like this:

```
// All soil layers:
[Nutrient].NO3.Denitrification.Rate.CERESDenitrificationTemperatureFactor.Values
// Top layer:
[Nutrient].NO3.Denitrification.Rate.CERESDenitrificationTemperatureFactor.Values[1]
// Top 3 layers:
[Nutrient].NO3.Denitrification.Rate.CERESDenitrificationTemperatureFactor.Values[1:3]
```

**Closed by hol430** 2020-10-21 23:42 UTC
Labels: bug, interface/infrastructure
