### ISSUE TITLE
Cannot execute Models.exe in Win 10 clean install

### ISSUE THREAD

**Issue by juancrescente** [APSIMInitiative/ApsimX#6948] opened 2021-11-12 16:51 UTC
I'm getting the following error whenever I want to execute Models.exe from the command line using any example. Any suggestiones?

`CompletedProcess(args='C:\\Program Files\\APSIM2021.11.11.6940\\bin\\Models.exe agpasture.apsim', returncode=2147516556, stdout='', stderr="Error:\n  An assembly specified in the application dependencies manifest (Models.deps.json) was not found:\n    package: 'Microsoft.Win32.SystemEvents', version: '5.0.0'\n    path: 'runtimes/win/lib/netcoreapp3.0/Microsoft.Win32.SystemEvents.dll'\n")
`

**Comment by femiguez** [comment] 2021-11-14 21:11
I see the same problem. One option is to install a previous version. I tried 2021.11.2.6421 and it runs without problems.

**Comment by hol430** [comment] 2021-11-14 23:48
Unable to reproduce - I tried version 2021.11.14.6871 and was able to run Models.exe without problems. I notice that:

- You're trying to run an old apsim (.apsim) file with apsim next gen. This will not work - you need to create an apsim next gen file (.apsimx). There is an importer tool in the gui which will do most of the work for you in terms of converting an old apsim file to an apsimx file.
- I'm not sure how you're invoking Models.exe but it looks like Models.exe is the first argument to another program. Can I ask what command you're actually invoking here? If I run `dotnet Models.exe ...`, I get a similar output to you, but running `Models.exe ...` works fine

**Comment by femiguez** [comment] 2021-11-17 19:32
I don't know what was going on there, but may be it was fixed somehow. I tested this using the Barley example. This is what I see:

version 2021.11.2.6421 runs fine from the command line
version 2021.11.11.6940 fails with the message above 
version 2021.11.16.6943 runs fine from the command line

There must be a bug there... Maybe it will re-emerge.

There tests were run under Windows from the command prompt.

**Comment by hol430** [comment] 2021-11-17 22:42
I pushed a tentative fix for this yesterday, but I don't think there are any releases out there yet which contain my fix. I hope that the problem will go away moving forward, but I'll leave this open for a bit longer, just to be sure.

I'm not sure why some versions work for you but others fail - did you test them all on the same computer?

**Comment by femiguez** [comment] 2021-11-17 23:39
Yes, it was all the same machine. Would it be helpful to provide any details?

**Comment by hol430** [comment] 2021-11-22 00:20
Out of interest, what is the output of these commands:

```
dotnet --list-runtimes
dotnet --list-sdks
```

**Comment by femiguez** [comment] 2021-11-22 22:50
I'm on Thanksgiving break here and won't have access to the laptop I tested this on until next week. Also, I did not build these, but rather download them "as is" from the download page. Thanks for asking!

**Comment by femiguez** [comment] 2021-12-04 21:37
sdks does not return anything. runtimes returns

```
Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by hol430** [comment] 2021-12-06 04:41
Thanks. I suspect it was only working on machines with the sdk installed. Regardless, I believe this should now be working on latest version.

**Comment by hol430** [comment] 2022-01-05 22:44
Closing as fixed (in releases from >= december 2021).

**Closed** 2022-01-05 22:44 UTC
Labels: question
