### ISSUE TITLE
HTML presenter slight font change when Run performed.

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#3934] opened 2019-06-12 06:35 UTC
I have noticed that there is a slight change in the font displaying the Simulation details in the HTML presenter view when you click run. There is obviously a value changed when run is selected. I have noticed this happens on other HTML pages as well. The look it changes to is best.

**Comment by hol430** [comment] 2019-06-13 02:39
The html view also seems to use the wrong font for me.

**Comment by hol430** [comment] 2019-06-13 05:57
@lie112 I'm having trouble reproducing your problem. For me, apsim uses the wrong font in the html views and although running the simulations causes the right-hand view does flicker, the font doesn't seem to change for me. #3942 should get apsim to use the correct font. When it is merged, can you tell me if it has an impact on your problem?

**Comment by lie112** [comment] 2019-06-13 23:46
I don't understand the implications of the changes made to HTMLView (changing browser font allocation) but this is clearly the reason for my observations.

My version now repeats your observation. I get a flicker when Run is selected, but the font remains the same size while previously it increased slightly.

The problem is, I now only get the default Times Roman font for all my HTML views rather than the clean sans font previously used.

Exploring the changes made to HTMLView.cs the new font allocation provides "Sans 10" as the value as this is what is provided in (MasterView as ViewBase).MainWidget.Style.FontDescription while the old line now deleted provided "Segeo UI 9" as that was the value from this.MainWidget.Style.FontDescription . I would suggest that "Sans 10" does not exists and my browser is using the default Times New Roman font. The font of the MasterView probably needs to be set, or I have set a font somewhere that was overriding your functionality and is now ignored.

Also the default white background I have built all my HTML summaries on has changed to the default window background (type of grey) and doesn't look as good for things like the summaryfile view, but this is likely the theme background. I also occasionally get an "Object not found" error while trying to set the BackgroundColour in HTMLView.cs when I click on a model in the tree that uses a HTML view. Is this all related to applying a dark theme?

I have not yet implemented any dark theme for CLEM components.
I can add a background-color setting to my html pages.

**Comment by lie112** [comment] 2019-06-17 05:01
Once I changed the font to Segoe UI in the change font section, everything worked great. Is it possible to set something other than Sans as the default? The HTMLView does not like Sans and reverts to default TimeNewRoman which looks awful.  When I change the system font to Segoe UI all works and it looks very professional through all my summary screens.
I suggest the default font should work out of the box.

**Comment by hol430** [comment] 2019-06-21 05:01
We can change the default font, however different fonts are available on different platforms. The only fonts which seem to exist on all three (of my testing machines) are 'sans', 'serif' and 'monospace'. On Linux, we already respect the system-wide default unless a custom font is chosen via the font dialog. On windows and mac, users are less likely to have a system-wide gtk theme setup, so we might have to choose a font arbitrarily and hope that it's installed on the user's system. The other problem of course is that as you've noticed, the browsers seem to have their own fontset which isn't exactly the same as the pango fontset. I'm not really sure what is the best thing to do here.

Regarding colours, I had a look at one of the clem examples and it's not very usable for me on Linux under the adwaita-dark theme:

![image](https://user-images.githubusercontent.com/36427516/59898387-ddfb7d00-9433-11e9-8afe-b74577e4142e.png)

This seems to be a result of the stylesheets that have been hardcoded into the clem code. The problem isn't the lack of dark theme support, it's the overriding of system-wide defaults. I've tried to make the html view respect the default colour scheme and fonts (controllable on windows primarily via the .gtkrc file we ship with apsim), but I guess this is being overriden by the css passed in from the clem components.

**Comment by lie112** [comment] 2019-06-21 05:57
That's odd. Below is my dark theme resource view. It seems yours is still using the light theme.
I am using the following code to alter my css for the two themes in various HTML presenters.
`            if (!Utility.Configuration.Settings.DarkTheme)
            {
                // light theme changes
            }
            else
            {
                // dark theme changes
            }
`

![image](https://user-images.githubusercontent.com/19215637/59900907-b4912000-9438-11e9-9c47-849a016ca8ae.png)

**Comment by lie112** [comment] 2019-06-21 06:00
Changing the font to "Segeo UI" in the settings/change font, gets rid of the default times roman
![image](https://user-images.githubusercontent.com/19215637/59901150-75af9a00-9439-11e9-96f2-d16a6d612167.png)

**Comment by lie112** [comment] 2019-06-21 06:02
I also realised that this isn't a system wide change, but it stored in the particular project apsimx file. 
Would be great to have a better default Windows font, at least try one and then drop back to Sans is not found.

**Comment by hol430** [comment] 2019-06-24 01:15
Ok, I've changed default font on Windows to Segoe UI 11. This will only be used if the user has never selected a font from the settings menu. If this font is unavailable for whatever reason, apsim should fall back to using sans.

The reason the clem html stuff doesn't work properly on Linux is that Linux users can't change theme inside apsim (the toggle theme button is hidden), so the `Utility.Configuration.Settings.DarkTheme` variable is always false. I did this because I expected most Linux users would prefer that Apsim respect their system-wide theme, however a few components (clem, graph, summary) change their displays slightly in dark mode. I've changed this so that the 'toggle theme' button is visible in Linux as well, but the only thing it does is change the DarkTheme variable - we still don't use any of our gtk .rc files on Linux. This fixes the clem (and graph) views on Linux.

**Comment by lie112** [comment] 2019-10-22 08:22
Delay in updating HTMLView font and background causes flicker!!

I have been trying to fix a problem where the HTMLView first draws the HTML with default font (times) and background colour (white). This happens in the browser.LoadHTML() of the HTMLViw.PopulateView(), but it isn't until after this call that the Font, Background and foreground colours are set. The old state appears to be displayed until the focus of the control is lost (another tab is produced or we move focus back to the treeview that was clicked) which can be a small delay producing a strong flicker as the new fonts and change is text placement happens.

You can repeat this problem by clicking the simulations branch of the simulation tree with a break point in HTMLView.cs at line 1005 (browser.LoadHTML(contents)). It is most obvious with the CLEM summary presenter. NOTE: This could be a Windows and IE Browser issue!!

Can someone explain when and where the browser final update that includes correct fonts and background colour happens and whether we can apply the details before the LoadHTML method of the browser so the first draw is correct and successful. 

I tried setting browser details before the LoadHTML method, but this didn't work and waited until the treeview again got focus.

**Comment by lie112** [comment] 2019-10-25 02:23
This problem also appears when editing a memo with the formatted lower display flipping between times and the formatted sans font as you type every second letter or so.

**Comment by lie112** [comment] 2020-03-05 00:11
Any progress on this problem?
It may have been lost down the list and doesn't seem to have been included in the stock sprint.
See @lie112  comment above on 22 Oct 19 
This is to do with rendering of GTK# components before properties are set and a second render.

**Closed** 2020-04-13 22:40 UTC
Labels: bug, interface/infrastructure
