### ISSUE TITLE
Setting NO3ppm & NH4ppm in the operations node

### ISSUE THREAD

**Issue by JodyBig** [APSIMInitiative/ApsimX#1862] opened 2017-08-15 01:37 UTC
Setting mineral N. In APSIM classic I would do this in the operations node:
2012-12-20  'Soil Nitrogen' set no3ppm = 2 2 1 1 1 1 1
2012-12-20  'Soil Nitrogen' set nh4ppm = 3 3 1 0 0 0 0 
Can this be included in APSIMX?

**Comment by zur003** [comment] 2017-08-15 03:42
For anyone pursuing this issue, the problem lies with SoilNitrogen, not with Operations. 

The syntax one needs to use in Operations is slightly different (and note that the variables are case-sensitive):

2012-12-20 [SoilNitrogen].NO3ppm = 2, 2, 1, 1, 1, 1, 1
2012-12-20 [SoilNitrogen].NH4ppm = 3, 3, 1, 0, 0, 0, 0

Operations will parse this as expected, and make an attempt to set the variables with the array of values provided. But when you try this, you will get the following messages from SoilNitrogen.Variables.cs:

An external module attempted to change the value of NO3 during simulation, the command will be ignored
An external module attempted to change the value of NH4 during simulation, the command will be ignored

So the Operations module is doing its job, but the SoilNitrogen module is explicitly disallowing the resetting of these values.

**Comment by rcichota** [comment] 2017-10-08 02:37
Sorry, just saw this issue. Following our work in classic apsim, adding urine patches to SoilNitrogen, the idea was to only use the event NitrogenChanged to modify the amount of N in the soil. In ApsimX this has not been carried through entirely, but blocking modification of the ppm has (it can only be used at the start of simulation). So, is changing values in ppm very important or can you use NH4/NO3 (kg/ha) instead?

**Comment by JodyBig** [comment] 2017-10-08 22:16
Hi Rogerio,

I could set NH4/NO3 instead of NO3_ppm/NH4_ppm.
Just to be clear, this currently does not work but will be impemented?
Would this confuse users if they can choose units for the initial parameters but not during setting?

Thanks
Jody

**Comment by rcichota** [comment] 2017-10-08 23:57
Hi Jodi, setting NH4/NO3 in kg/ha should be working as it is. There has been some discussion on the best way to deal with different units (or which one should be actually used), but I don't think we got far in actually setling for a defined solution. In classic Apsim we needed to control how changes in N are made, thus having only one way (the NitrogenChanges event) was ideal. This should be true in ApsimX if the urine patch capability is to be used, but this implies changing a few modules and also Dean doesn't want to use events (so no solution yet)...  Hope this helps

**Comment by JodyBig** [comment] 2017-10-09 01:15
Hi Rogerio

Thanks for getting back to me.
It all sounds logical and sticking to kg/ha for all inputs/outputs probably makes a lot of sense.

Cheers

Jody Scott Biggs
Senior Experimental Scientist
Agriculture Flagship
CSIRO
E jody.biggs@csiro.au T +61 7 3214 2413
CSIRO – Agriculture Flagship, GPO Box 2583, Brisbane Q 4001
www.csiro.au

PLEASE NOTE
The information contained in this email may be confidential or privileged. Any unauthorised use or disclosure is prohibited. If you have received this email in error, please delete it immediately and notify the sender by return email. Thank you. To the extent permitted by law, CSIRO does not represent, warrant and/or guarantee that the integrity of this communication has been maintained or that the communication is free of errors, virus, interception or interference.

**Comment by rcichota** [comment] 2018-02-06 20:33
Further update, @JodyBig 
Val is pushing to have the urine patch capability fully implemented in ApsimX, so Dean and I have made a few changes to make that happen (well, mostly Dean really). As I said earlier, to allow the patch thing to work SoilNitrogen needs to know which model is making changes in N. So, Dean has introduced a SetX() method that should be used to change the values for any N form in the soil. It is pretty similar to the way we were setting the values before (still doing in kg/ha). One just has to add an 'enum' to tell SolNItrogen which model is making the change. So, for example to change NO3, instead of:
**Soil.SoilNitrogen.NO3 = newValues;**    // where newValues is an array
you should now use:
**Soil.SoilNitrogen.SetNo3(SoluteManager.SoluteSetterType.Fertiliser, newValues);**
This is valid for the three forms (Seturea, SetNH4 and SetNO3).
Hope this helps, can we then close this issue or you thing there's more that needs clarifying/done?
Cheers

**Comment by JodyBig** [comment] 2018-02-07 00:22
?Hi


It sounds like it is undercontrol. I assume it has been tested? If so I'm happy if the issue is closed.


Jody Biggs
________________________________

**Closed** 2019-01-11 05:59 UTC
Labels: interface/infrastructure, newfeature

**Comment by JJguri** [comment] 2020-09-04 02:21
In the apsimx file attached, you will find an updated version of the reset module where I incorporated a function to reduce the SoilNH4.kgha[1] due to volatilisation. I have created a series of dependent variables such as soil water available, wind speed, and percentage of coarse sand which affects the % of reduction based on this [paper](https://www.publish.csiro.au/sr/sr14107). I also created 2 date variables that define the period when the volatilisation will occur from the fertilisation date (in the example one week after fertiliser application).

The problem is related to the Patch[base].deltaNH4 variable. When I run a 5-year sugarcane simulation, it works well during the first year, please see the graph ‘N1_1990short’ from 15-Oct to 22-Oct (7 days after fertiliser application). However it crashes during the next year and, for some reason, the crop is not getting the fertiliser right (1991). Below is the exact error:

`Patch[base].deltaNH4, attempt to change nh4[1] to a value(-1.0170061864527) below the fatal threshold (-1E-06)`

[sugarcane.zip](https://github.com/APSIMInitiative/ApsimX/files/5172301/sugarcane.zip)

**Comment by hol430** [comment] 2020-09-04 04:14
Well I don't really understand the background here but you're calculating the new nh4 value as `double newNH4 = currentNH4 - (currentNH4 * vol_red);`. On the day of the error, vol_red is greater than 1, so newNH4 comes out as negative. If it helps, here are some of your other variables on the day of the error.

```
vol_red = 2.30248801174286
CoarseSand = 10
WindSpeed = 2
avail_sw = 11.8723217787821
```

One way of debugging this problem might be to print some of these values to the summary file. E.g.

```csharp
if (newNH4 < 0)
{
	Summary.WriteMessage(this, string.Format("newNH4 value is negative. newNH4 = {0}, vol_red = {1}", newNH4, vol_red));
}
```

Then after the simulation runs, your diagnostics will be in the summary file.

**Comment by JJguri** [comment] 2020-09-04 05:52
thanks @hol430. Can I export `vol_red` and `avail_sw` as outputs? How would be the easy way to do that?
Seems I need to restrict the function only for `newNH4 > 0` and `vol_red < 1`. vol_red cannot be > 1 because is the proportion of NH4 volatilised (0-1).

**Comment by hol430** [comment] 2020-09-06 22:19
This ought to make `vol_red` outputtable from report, e.g. as `[Reset].Script.vol_red`. The only change is to add vol_red as a public property of the script.

```csharp
        public double vol_red { get; set; }

        // Calculate the adjusted values of the NH4 by soil layer
        private void CalcNewNH4()
        {
            double[] LL15 = MathUtilities.Multiply(soil.LL15, soil.Thickness);
            double[] DUL = MathUtilities.Multiply(soil.DUL, soil.Thickness);
        
            int nlayr = GetLayerIndex(FASWDepth);
            double cumdep = MathUtilities.Sum(soil.Thickness, 0, nlayr, 0.0);    // tricky function that sums up to before nlayr

            double part_layer = MathUtilities.Divide((FASWDepth - cumdep), soil.Thickness[nlayr], 0.0);

            // note that results may be strange if swdep < ll15
            double avail_sw = (MathUtilities.Sum(soil.Water, 0, nlayr, 0.0) + part_layer * soil.Water[nlayr])
                            - (MathUtilities.Sum(LL15, 0, nlayr, 0.0) + part_layer * LL15[nlayr]);

            vol_red = (11.29 + (0.31 * CoarseSand) - (2.78 * WindSpeed) + (avail_sw * 18.65))/100;

            double currentNH4 = SoilNH4.kgha[1];

            double newNH4 = currentNH4 - (currentNH4 * vol_red);
            if (newNH4 < 0)
            {
            	Summary.WriteMessage(this, string.Format("newNH4 value is negative. newNH4 = {0}, vol_red = {1}", newNH4, vol_red));
            }
            myNewNH4 = new double[] {newNH4};
        }

```
