### ISSUE TITLE
Error from Post Simulation Tools

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#3808] opened 2019-05-02 08:46 UTC
If an APSIMX file has several simulations, and objects that do post simulation analysis (e.g. probability and morris) you get an error if you run a single simulation that does not populate the tables used by the post-simulation tools.
e.g. if a probability tool on datastore points to a HarvestReport but no simulation is run which outputs data to that table.  Or if a Morris is in the APSIMX file, but you do not run it or any simulation that writes to an output called "Report".

e.g.
1 errors thrown from post simulation tools:

System.Exception: Error in probability model Probability: table 'MaizeHarvestReport' does not exist in the database.
   at Models.PostSimulationTools.Probability.Run(IDataStore dataStore) in C:\APSIMX\Models\PostSimulationTools\Probability.cs:line 53
   at Models.Core.Runners.RunOrganiser.RunPostSimulationTools(IModel rootModel, IDataStore storage) in C:\APSIMX\Models\Core\Runners\RunOrganiser.cs:line 147

**Comment by hol430** [comment] 2019-05-02 22:14
Is this a bug? It seems like a reasonable error message to me.

**Comment by hut104** [comment] 2019-05-02 23:14
I guess it seems strange to get an error message from something that has not been run.  I had a file with three simulations and if I ran only the third, I received errors talking about the other two simulations.  Furthermore, in many cases we handle empty data tables without throwing exceptions.

**Comment by hol353** [comment] 2019-05-03 00:09
This is a known problem that will be fixed when I get around to refactoring the run simulation code soon.

**Comment by hol430** [comment] 2019-05-03 00:13
What are you going to do to 'fix' this? The error message is not coming from something which has not been run, it's coming from the post simulation tool which is being run. The problem is that the post simulation tool really has a dependency on one or more simulations. Maybe the post simulation tool should only get run if we run the entire file.

**Comment by hol353** [comment] 2019-05-03 01:06
I think the problem is that when you run a single simulation (or a subset) of an experiment. It runs differently somehow and the 'report' table isn't quite right and the post simulation tools fail sometimes.

**Comment by hol430** [comment] 2019-05-03 01:12
I've run into this without an experiment being involved; let's say the post simulation tool is a PredictedObserved model. Let's say the predicted table is called HarvestReport, and is generated by simulation A, but you run simulation B instead. The HarvestReport table doesn't exist, because simulation A has not been run. In this case it might make sense for the PredictedObserved tool to only be run if simulation A is run.

**Closed** 2020-06-08 21:12 UTC
Labels: needs-clarification
