### ISSUE TITLE
DataStore database duplicate records in _Messages table

### ISSUE THREAD

**Issue by her123** [APSIMInitiative/ApsimX#3609] opened 2019-03-13 03:41 UTC
Consecutive runs appear to add duplicate records to the _Messages table. They either need a different index or should be cleaned up before the run.

**Comment by hol353** [comment] 2019-03-13 04:15
I have a fix for this on #3604. Just need to get it to run green.

**Comment by rcichota** [comment] 2019-03-13 20:37
There seem to a an issue with the order they are printed. I was trying to debug a manager script controlling a crop rotation, in there I have a nested loop going through a array (ultimately matching available and selected crops). The simplified version is below. I'd expect that I would get the repetition of the list, not the duplicate of each value:
```
availableCrops = new string[]{"SpringWheat","AutumnWheat","SpringBarley","AutumnBarley","FodderBeet","Oats"};
for (int i=0; i<2; i++)
{
   for (int j=0; j< availableCrops.Length; j++)
   {
      summary.WriteMessage(this,"crop: " + availableCrops[j]);
   }
}
```
This is what I get in the Summary:
crop: AutumnBarley
crop: AutumnBarley
crop: AutumnWheat
crop: AutumnWheat
crop: FodderBeet
crop: FodderBeet
crop: Oats
crop: Oats
crop: SpringBarley
crop: SpringBarley
crop: SpringWheat
crop: SpringWheat

**Comment by rcichota** [comment] 2019-03-13 20:41
I also have two managers (RotationManager and SowCrops), the second is triggered by the first (using the "Set()" method). If I set up a message to be written in both of them (being careful with the order they are triggered, first in RotationManager then in SowCrops), I get the message from the second manager first...

**Closed** 2019-03-13 22:33 UTC
