### ISSUE TITLE
Upgrade-Downgrade not working

### ISSUE THREAD

**Issue by sme016** [APSIMInitiative/ApsimX#7312] opened 2022-05-30 12:08 UTC
For the few days I have noticed that I can't upgrade APSIMx on my Windows system. The error message is as follows.

System.Exception: Encountered an error while updating registration information. Please try again later.
 ---> System.Net.WebException: The remote server returned an error: (405) Method Not Allowed.
   at System.Net.HttpWebRequest.GetResponse()
   at APSIM.Shared.Utilities.WebUtilities.CallRESTService[T](String url) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\APSIM.Shared\Utilities\WebUtilities.cs:line 98
   at UserInterface.Views.UpgradeView.WriteUpgradeRegistration(String version) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\ApsimNG\Views\UpgradeView.cs:line 522
   at UserInterface.Views.UpgradeView.OnUpgrade(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\ApsimNG\Views\UpgradeView.cs:line 329
   --- End of inner exception stack trace ---
   at UserInterface.Views.UpgradeView.OnUpgrade(Object sender, EventArgs e) in C:\Users\ContainerAdministrator\AppData\Local\Temp\ApsimX\ApsimNG\Views\UpgradeView.cs:line 333

**Comment by hol353** [comment] 2022-05-30 23:05
Hmm I just upgraded my released version of ApsimX (using the upgrade button in the GUI) to a newer version. It worked for me. Can you try it again?

**Comment by sme016** [comment] 2022-05-30 23:13
Thanks for working on this.

I had versions 2040 and 2043 on my computer this morning.

The same message came up both:
When I tried to downgrade from 2043 to 2042. Then I uninstalled 2043 entirely, and
When I tried to upgrade from 2040 to 2043.


***@***.***

**Comment by hol353** [comment] 2022-05-30 23:34
It must be because they are very old versions (2017?). If you re-download Next Gen. from www.apsim.info then it will work.

**Comment by zur003** [comment] 2022-05-30 23:36
@hol353 Or maybe not. I'm seeing the problem, even though I'm starting with 2022.5.7040.

**Comment by sme016** [comment] 2022-05-30 23:42
Like Eric, my version numbers were recent too, but I should have given you the full version numbers I was talking about, e.g. 2022.5.2040.0

**Comment by zur003** [comment] 2022-05-30 23:47
There's some code here that should probably be revised in any case. The call stack is indicating a problem in System.Net.HttpWebRequest.GetResponse, but Microsoft has deprecated use of HttpWebRequest. See [https://docs.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated](https://docs.microsoft.com/en-us/dotnet/core/compatibility/networking/6.0/webrequest-deprecated) . We should fix this as part of moving to .Net Core 6.

**Comment by hol353** [comment] 2022-05-31 00:49
At what point do you get the error? Can you paste a screenshot?

**Comment by zur003** [comment] 2022-05-31 01:38
![image](https://user-images.githubusercontent.com/11879340/171075727-0640f58e-2afd-4d04-a2e0-e191a4e4a18f.png)

Pressing the more information button gives:
![image](https://user-images.githubusercontent.com/11879340/171075880-461440bf-3bbb-4a5c-880a-f2e9c04ea9b0.png)

**Comment by hol430** [comment] 2022-05-31 01:45
UpgradeView.cs, change line 522 to PostRestService (as in the try block). The actual error coming from line 517 is being hidden by this typo, although you could probably catch it with a debugger.

**Comment by hol353** [comment] 2022-05-31 02:03
Thanks Drew. Yes, when I was debugging this I discovered the same fix. There is a problem in the registrations api which I'm working on now.

**Comment by hol353** [comment] 2022-05-31 02:50
@sme016. It looks like the problem is that you aren't regestered in the APSIM registrations database. I'm not sure how that could happen given you have APSIM installed. I do notice that we registrations expire every three years, after which you need to re-agree to the license terms. Perhaps this is what happened. I'll work on a fix for APSIM GUI / Upgrade form to detect when this happens and re-register you.

A workaround is to go to www.apsim.info downloads page and go through the steps to re-download apsim. Once you get to the list of downloads I think you will then be registered and can then go back to APSIM Upgrade form and it should work.

**Comment by sme016** [comment] 2022-05-31 02:55
Thanks

**Comment by zur003** [comment] 2022-06-08 07:58
I think there's another problem that was introduced recently. A commit made on 22 April removed the line in UpgradeView.cs which set the versionNumber variable, but if that variable is not set, the downloaded installer will not be executed.

**Comment by hol353** [comment] 2022-06-08 23:32
Hi @zur003 great to see you still helping out on APSIM!!!! 

I was able to successfully upgrade a January released version of APSIM to a very recent one using the Upgrade button in the GUI.

**Comment by her123** [comment] 2022-06-09 22:22
![Screen Shot 2022-06-10 at 8 20 44 am](https://user-images.githubusercontent.com/11879671/172954947-00344e08-a4dc-49db-88b9-e991610a7ecb.png)

Update on OSX also fails

![Screen Shot 2022-06-10 at 8 22 16 am](https://user-images.githubusercontent.com/11879671/172955021-a0e827a0-b769-40c0-906d-b9354fb56e8e.png)

**Closed** 2022-06-12 21:50 UTC
Labels: bug, interface/infrastructure

**Comment by sme016** [comment] 2022-10-11 07:52
Here’s the screenshot again, which comes immediately after clicking on ‘Yes’ at the dialog box ‘Are you sure’

***@***.***

**Comment by zur003** [comment] 2022-10-11 08:46
@sme016 - Are you asking for this to be re-opened? If so, what version are you upgrading from?

**Comment by sme016** [comment] 2022-10-12 03:31
No - don't reopen this issue for me. It was fixed some time after I originally raised the issue. It appears I made a comment about 20 hours ago, but it wasn't me. It looks like phishing. I haven't been near GitHub or APSIM for quite some time, but aim to get back to it in November.
