### ISSUE TITLE
Adding a new layer to Soil.Water cause unhandled exception

### ISSUE THREAD

**Issue by jbrider** [APSIMInitiative/ApsimX#836] opened 2016-05-11 23:32 UTC
soil.CalcPAWC checks the number of layers against the number of LL and DUL and throws an exception if they are different. This means you cannot add a new layer to the Soil.Water grid.

**Comment by zur003** [comment] 2016-06-24 06:37
See also #31. I'm not sure whether than was ever resolved.

**Comment by zur003** [comment] 2016-06-30 01:36
Also #594 appears to be a duplicate of this issue.

**Comment by hol353** [comment] 2016-08-04 23:26
@zur003 Do we also close issue 31 and 594?

**Closed** 2016-08-04 23:25 UTC

**Comment by zur003** [comment] 2016-08-05 00:23
I would close 594, but not 31, which is a somewhat different issue.
