### ISSUE TITLE
Drop down list view not working in manager properties view

### ISSUE THREAD

**Issue by HamishBrownPFR** [APSIMInitiative/ApsimX#2491] opened 2018-03-21 18:23 UTC
If a enum variable has the below tag above it in a manager script, the property view should display a drop down list to select a member.  This is not working.  See the sowing rule in the manager tool box for example 
[Display(DisplayType = DisplayAttribute.DisplayTypeEnum.CultivarName)]

**Comment by HamishBrownPFR** [comment] 2018-03-21 18:28
Sorry, this is actually working, just the list selector doesn't show up until you hit enter or double click in the property cell.   It would be better if the list select arrow were always visiable for these sort of properties in the manager properties tag and that the list becomes visible on a single click.
Probably related to this issue is the need to double click or hit enter to be able to edit any grid box in the UI.  I find this counter intuitive as most software makes a test box editable with a single click

**Comment by hol430** [comment] 2018-04-05 03:06
> most software makes a test box editable with a single click

In Excel, clicking on a cell will put a border around the cell, but will not actually put the cell into 'edit mode' until you either double click or start typing.

e.g. After clicking on the cell:
![excelselection](https://user-images.githubusercontent.com/36427516/38343942-1ca296c2-38ca-11e8-8891-866b09ace103.png)

After a double click/key press while the cell is selected:
![excelcaret](https://user-images.githubusercontent.com/36427516/38343831-73ee8bee-38c9-11e8-8207-0fac3bf410ca.gif)

I can change the grid so that, as you suggested, the text box is in edit mode after a single click. Alternatively, I can emulate Excel and select the cell after a click, and enter edit mode after another click (or keypress). This second option is more or less what we have now.

Which option do we want to go for here? It's worth noting that in both cases, you will be able to click on a cell once and start typing. 

It would also be great (particularly if we go for option 2) to be able to select a cell without the rest of the row, so that it's obvious that you've actually selected a specific cell. This would probably be difficult though - if it's possible at all. @zur003 Have you attempted anything like this with a TreeView before?

Sorry to hijack your original issue by the way - I am looking into it

**Comment by HamishBrownPFR** [comment] 2018-04-05 04:41
Thanks Drew.

What ever is best from an implementation point of view.   So long as we don't have to do so much clicking and are better aware of where we are in the grid I am happy.

**Comment by rcichota** [comment] 2018-04-05 10:53
I'd think that making clear which cell is actually selected would be the greatest improvement. This highlighting of the whole line is really not good. Currently one has to select and either double click or press 'enter' to actually edit the cell, being able to just type as in excell would be my suggestion as it follows the behaviour people are used to (at least in Windows).

**Comment by zur003** [comment] 2018-04-06 01:41
I'm still having problems with the GUI crashing when I click on a header with the shift key held down.

**Comment by hol430** [comment] 2018-04-06 01:48
This works for me both on the developer build and on the latest release (2394). Are you shift clicking the header when other columns are selected? When no other columns are selected?

**Comment by zur003** [comment] 2018-04-06 01:58
I'm seeing it with release 2018.4.4.2394, and actually it's happening with or without the shift key. I just open the Wheat example, expand the tree and select "Clock" then click on the "Value" header (with no prior grid selection). The application falls over immediately.

**Comment by hol430** [comment] 2018-04-06 02:07
OK now I am confused because I did exactly as you did on the 2018.4.4.2394 release build and it worked perfectly - with and without the shift key.

**Comment by hol430** [comment] 2018-04-06 02:12
Actually I've found an issue with the wrong column being selected when Apsim is not maximised - this may be the cause of your issue if you're not running it maximised. I will look into it.

**Comment by zur003** [comment] 2018-04-06 02:13
I don't see the same problem when running on Ubunutu, but find that the "selected" column is not the one whose header I clicked.
There's also an annoying problem with the "automatic" editing. Suppose my intent is to select a range of rows. If I click (but don't start editing) a cell on the first row, then press the shift key (in anticipation of clicking on a different row to select the range between them), the starting cell goes into editing mode and throws away its original contents. I haven't looked into it, but I think the initiation of editing needs to check to be sure that the keypress is for a character, rather than being a shift, control, arrow, or other such key.

**Comment by hol430** [comment] 2018-04-06 02:14
Yeah my pull request I made a few minutes ago should fix that auto editing bug by doing exactly as you suggested.

**Comment by zur003** [comment] 2018-04-06 02:16
Interesting. Maximizing the application gets rid of the crashes. I wonder if there's some problem with use of screen vs. application co-ordinates???

**Comment by zur003** [comment] 2018-04-06 02:41
I think you can avoid having to deal with co-ordinates. In the HeaderClicked handler, the "sender" argument identifies the Button that was pressed. That Button will be a child of the treeview control, so you can step through the children of the treeview widget, counting "buttons" as you go, until you find the "sender" of the click; the number of buttons counted when you reach your target should give you the column number. I know this is not very tidy, and makes assumptions about what Gtk is doing internally, but I think it will work.

**Comment by hol430** [comment] 2018-04-06 02:51
OK that works, thanks. It's not real tidy, but the way that I've responded to column button press events isn't real tidy anyway. And it (appears to) work better than using coordinates anyway.

**Comment by hol430** [comment] 2018-08-23 01:26
Closing this now, as the original issue has since been resolved.

**Closed by hol430** 2018-08-23 01:26 UTC
Labels: bug, interface/infrastructure
