### ISSUE TITLE
Manager script  error messages

### ISSUE THREAD

**Issue by pjinnes** [APSIMInitiative/ApsimX#5913] opened 2020-12-02 22:21 UTC
If I write or update a manager C# script and miss spell a variable name or similar the only indication I get is the Parameters tab goes blank and the script doesn't run when I do the simulation. Is there some way of getting error messages displayed when I modify the script?

**Comment by hol430** [comment] 2020-12-02 22:31
Ctrl + t while you're editing the script will compile it, and any errors will be displayed in the bottom panel. Otherwise, the script will compile whenever the text editor widget loses keyboard focus - so when you click on another node in the simulations tree, or when you click on the parameters tab.

I just tested and the parameters tab doesn't go blank for me when there is a compile error - so perhaps the problem is specific to your script. If you upload your script or file, I'll take a closer look.

**Comment by pjinnes** [comment] 2020-12-02 22:52
[petesTest.apsimx.txt](https://github.com/APSIMInitiative/ApsimX/files/5632511/petesTest.apsimx.txt)
I put in bad comment line to test the script 'petes SMAP Assimilation', don't see bottom panel or error messages, how do I display that?

**Comment by hol430** [comment] 2020-12-03 22:44
Thanks @pjinnes, definitely a bug. Should be fixed by #5919.

**Comment by hol430** [comment] 2020-12-03 23:03
As for the second part of the issue about not seeing the lower panel, it can be dragged up/down, so I'm guessing yours has somehow been dragged so far down as to be invisible. If you move your mouse to the bottom of the screen you should be able to drag it up so it's visible again.

![apsim-1](https://user-images.githubusercontent.com/36427516/101098920-7f1dc980-360f-11eb-9e92-75a05adc2fef.gif)

**Closed** 2020-12-03 23:18 UTC
Labels: bug, interface/infrastructure
