### ISSUE TITLE
No error message when the mis-spelling variable reference 

### ISSUE THREAD

**Issue by byzheng** [APSIMInitiative/ApsimX#3767] opened 2019-04-18 01:12 UTC
Step to reproduce this problem. See example below

* Open wheat example, create replacement and copy wheat.json into replacement.
* Copy "Photosynthesis" under "Leaf" into "Photosynthesis_RUE"
* Create "VariableReference" as "Photosynthesis" and add value as "[Photosynthesis_RUE"

The value of "VariableReference"  is missing right bracket. APSIM doesn't give any error. 

However, the biomass is close to zero. 

[test.zip](https://github.com/APSIMInitiative/ApsimX/files/3092074/test.zip)

**Comment by hol430** [comment] 2019-04-18 01:20
I haven't looked into this (and probably won't get time today), but it sounds like this problem will be fixed by Neil's pull request #3591

**Comment by hol430** [comment] 2019-12-10 02:26
Duplicate of #3554

**Closed by hol430** 2019-12-10 02:26 UTC
Labels: bug, interface/infrastructure
