### ISSUE TITLE
Geolocator api key is expired

### ISSUE THREAD

**Issue by peter-devoil** [APSIMInitiative/ApsimX#9457] opened 2024-11-20 01:14 UTC
### What happened?

When looking for a soil via place name, the user is told "Cannot find a latitude/longitude from the specified place name.", no matter what town they type in.

It appears the error from google relates to an invalid key:
![image](https://github.com/user-attachments/assets/2ee7dfa7-ccfb-4d1a-90d7-0b5c03a421ac)

The key is defined [here](https://github.com/APSIMInitiative/ApsimX/blob/b2546ea47df443ba7384f7b11408c78453d06b8f/ApsimNG/Presenters/SoilDownloadPresenter.cs#L34)

### What Operating System are you on?

Linux

**Comment by zur003** [comment] 2024-11-20 06:06
This is a duplicate of #9282. Fixing it should be trivial. All that is needed is a new Google geocoding access key. This needs to be done by someone on "the inside" who has access to the APSIM Initiative Google account.

**Closed** 2024-11-25 01:31 UTC
Labels: Bug
