### ISSUE TITLE
APSIM upgrade version

### ISSUE THREAD

**Issue by lie112** [APSIMInitiative/ApsimX#6114] opened 2021-02-01 05:37 UTC
It seems the latest upgrade available to users is old 2021.20.1.5937 while Jenkins suggests there are upgrades created on 1 Feb 2021.

Changes to the upgrade presenter have also removed the ability to look at upgrades available list while working in developer environment (now only get a _Successfully upgraded all files_ message). I am able to see http://apsimdev.apsim.info:8080/jenkins/job/PullRequest_v2/ but this doesn't appear to match the builds available to users.

As CLEM users are all upgrading regularly I need to be able to track available upgrades and let them know when CLEM fixes are available while they are currently using and awaiting fixes in APSIM.

**Comment by hol430** [comment] 2021-02-01 05:46
Yep, there were some problems with one of the build servers which I think are now fixed. There's a release job nearing completion now, hopefully there should be an upgrade out in an hour or so.

> Changes to the upgrade presenter have also removed the ability to look at upgrades available list while working in developer environment (now only get a Successfully upgraded all files message).

This sounds like you might have accidentally clicked 'upgrade resource files' instead of 'upgrade'? This is working for me.

**Comment by lie112** [comment] 2021-02-01 06:11
Oops, you're so right.
I'm trying to work with 1920x1080 and everything falls off second monitor.
Will just wait to see if an new upgrade appears before closing this issue.

**Closed** 2021-02-01 23:11 UTC
Labels: interface/infrastructure

**Comment by lie112** [comment] 2021-02-02 02:11
As far as I and users can tell the latest upgrade available is still 2021.01.20.5937 Markdown view improvements - tables
Can you look into getting the upgrades to show as I need latest fixes for a workshop tomorrow morning?

**Comment by hol430** [comment] 2021-02-02 02:48
Version 2021.02.02.6114 is now released, which is up-to-date as of today. The release builds seem to be working again...for now.

**Comment by lie112** [comment] 2021-02-02 05:00
Thanks.. I see the new upgrades now
BUT
One of our users tried to do the upgrade from the two option showing and he said it went very quick but did say uninstalling APSIM
Now he is back at a very old version with no upgrades available
![error 1](https://user-images.githubusercontent.com/19215637/106554575-35942100-6563-11eb-82f4-750d97c8c783.jpg)

Another user Di Prestwidge just got 
![upgrade error 2](https://user-images.githubusercontent.com/19215637/106554501-11384480-6563-11eb-9df7-693754c131f6.png)

**Comment by hol430** [comment] 2021-02-02 05:17
I've shuffled around a few files, and I think the problem is fixed now. Can you try again? (Anyone who has installed the old version might need to uninstall and download a fresh copy if the upgrade UI isn't working.)

I would guess that this may be related to already having already released a version 877 several years ago. The older version was downloaded and installed. Perhaps that version wasn't digitally signed...if so, that may be why it's tripping your antivirus.

**Comment by lie112** [comment] 2021-02-02 05:47
One user just tried to upgrade:
"2021.02.02.6114  appears on the upgrade panel, but when I install it I get APSIM 2018.6.13.877"

**Comment by hol430** [comment] 2021-02-02 23:22
Could that have occurred before I made my changes yesterday? I've tried upgrading from several computers this morning and haven't had any problems with the 877 version.

**Comment by lie112** [comment] 2021-02-02 23:54
I'll let you know as all of today's workshop in Brisbane will have to get upgraded to a working version.
