### ISSUE TITLE
Right panel freezes

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#8505] opened 2023-12-15 00:28 UTC
### What happened?

Sometimes right panel freezes and does not change when the focus is moved from one node to another node. See the video.
https://github.com/APSIMInitiative/ApsimX/assets/39573622/95358710-8d12-429a-95c4-e214120a100f

### What Operating System are you on?

Windows

**Comment by par456** [comment] 2023-12-15 04:22
This has been a tricky one because it's appeared randomly for a few months now. I've not seen it on my machine, but @hol353 and @hut104 have both also experienced it.

They've suggested it happens when the file has open and in use for a while, but don't know of a specific action that causes it to happen. They were able to show it today when coming back to the gui after leaving it idle for 30 minutes today.

I've put a pull request in to try and fix this, but without a way to replicate the problem, it's a bit hard to know if it will or not. I'll leave this issue open for a bit and see if it keep happening to other people.

If someone does know of a way to force it to break like this, let me know.

**Comment by BrianCollinss** [comment] 2023-12-16 08:31
Saving the file will move the focus to the selected node, but then it freezes again. I thought it might give you some clue.

**Comment by ric394** [comment] 2023-12-18 23:48
I've managed to reproduce the error by trying to rename a node then pressing save, similar to what @BrianCollinss described. It doesn't cause an error every time, but I noticed that it happens more frequently when a single-click on a node makes the node go into edit mode.
Here is a video with my findings:

https://github.com/APSIMInitiative/ApsimX/assets/123442863/e236eaa6-7a4e-4429-a7b9-bd2f2c7e810c

**Comment by BrianCollinss** [comment] 2023-12-20 00:32
I came across an old Issue about renaming and all kinds of issues that it would cause. I still have similar problems when I rename nodes. Sometimes, instead of the node I want to rename, another node which was selected before is renamed.

**Comment by par456** [comment] 2024-01-08 00:25
Thanks Julian, that one helps a lot.

Just tested and was able to replicate that on the master branch, and the fix I implemented in the pull request above fixes that bug. I'll mark it to be merged in and it might finally fix this problem.

**Closed** 2024-01-09 05:56 UTC
Labels: bug
