### ISSUE TITLE
Manager scripts are creating phantom script nodes in the GUI

### ISSUE THREAD

**Issue by sno036** [APSIMInitiative/ApsimX#8673] opened 2024-02-21 22:50 UTC
### What happened?

As attached

![image](https://github.com/APSIMInitiative/ApsimX/assets/12176269/f4a061b6-59a2-4756-9224-29dc01e0fb16)
[ExamplePhantomScripts.zip](https://github.com/APSIMInitiative/ApsimX/files/14365971/ExamplePhantomScripts.zip)

### What Operating System are you on?

Windows

**Comment by sno036** [comment] 2024-02-21 22:52
And they seem to breed prolifically! Copied that script to another simulation and ...

![image](https://github.com/APSIMInitiative/ApsimX/assets/12176269/6a3cbb4e-442c-4b9a-83ef-1315c516e4e6)

**Comment by par456** [comment] 2024-02-22 01:27
Once that is merged in, you can fix your file by:

> To fix a file that was opened on the previous version and has Script children, open the file, save and close it and then when it's reopened everything should be correct again.

**Comment by peter-devoil** [comment] 2024-03-05 03:44
The problem is still there if your simulation's managers are making anything not called a "Script", eg Examples/Tutorials/EventPublishSubscribe:

![image](https://github.com/APSIMInitiative/ApsimX/assets/1924386/a60eb3dd-6656-4306-886b-3620f45905b6)

**Closed** 2024-03-06 05:36 UTC
Labels: Bug, Software
