### ISSUE TITLE
temporary db files left behind

### ISSUE THREAD

**Issue by rcichota** [APSIMInitiative/ApsimX#3989] opened 2019-07-02 02:49 UTC
This is as much a question as an issue. I noticed that there are now some temporary db files that are not cleaned up after a simulation run (see figure). These can be deleted manually without problem, but shouldn't this be done by Apsim/Sql? This can be cumbersome when running hundreds of simulations and can mess up some R scripts we have. Was it intended that these files were left behind, or is it an indication of something else wrong, or is simply a side-effect of latest sql version?
![image](https://user-images.githubusercontent.com/12175986/60479061-9b119300-9cd8-11e9-9688-c2a68f2e04ee.png)

**Comment by zur003** [comment] 2019-07-02 06:07
Those should be cleaned up automatically when the database is closed (SQLIte does the cleanup, not Apsim). If they're not being removed, it's a sign that the database isn't being closed properly. If I recall, it all gets a bit tricky because of the .net garbage removal mechanism, so database objects can be kept open longer than you might expect. Or maybe we have a bug somewhere that's keeping garbage collection from working as expected.

**Comment by rcichota** [comment] 2019-07-02 21:53
This seem to be only an issue when the simulations doesn't fully finished. Frank here noticed that when running in our HPC environment, the only files of that type left behind are from the simulations that for some reason did no run properly (maybe a linux thing because re-running them will get things cleaned up). 
Running on my PC I noticed that those files are created as soon as the simulation is opened and are delete when APSIM is closed (not when the simulation is closed, as I'd expect). However, if the simulation is stopped before it finishes (using the stop button), the files will not get cleaned up, even after closing APSIM...  Not sure if this is an issue that needs attention or simply a 'feature' of how Apsim uses sql...

**Comment by hol430** [comment] 2019-07-08 03:08
When #3999 is merged, these temporary files will be cleaned up properly when you close a tab, even if you cancel a run (or fail a run due to errors). I'm unable to reproduce the second part of the problem however - if a simulation throws an error when run from the command line, the .db-wal files are still cleaned up properly. Haven't tested on Linux though - perhaps it is a peculiarity related to mono's garbage collector. Will look into it.

**Comment by zur003** [comment] 2020-06-12 03:53
This may need to be re-opened, as it seems to be breaking Jenkins. I should note that I encountered something similar when running tests of Models.exe compiled in .Net Core, The DataStore wasn't closing at the end of a command-line run. I added some Dispose code to let me run my examples, but didn't merge this into the main branch, as I wasn't sure it was the "right" solution to the problem.

**Comment by hol430** [comment] 2020-06-12 03:57
Yeah, the strange part about this one is that the failing test runs for me even when I checkout the same commit that jenkins is running. I was also seeing some weird compilation errors in some earlier pull requests today, related to some files being locked.

**Comment by zur003** [comment] 2020-06-12 04:00
@hol430 - Shall I try applying the modifications I made for my ,Net Core 3 builds? If they work, then you and @hol353 could review them to see whether they make sense,

**Comment by hol430** [comment] 2020-06-12 04:03
Yeah it sounds like a change we probably want in apsim anyway so might as well.

**Closed** 2020-06-14 21:25 UTC
Labels: bug, interface/infrastructure

**Comment by frank0434** [comment] 2020-06-21 09:36
Would like to share a Python solution to close the `db` connection properly for the previous build of ApsimX.
I have a build just 2 days before the fix #5294 and already triggered 8K+ simulations via command line. There were about 7600 simulations have these two `temp` files and a corresponding `.db$`.
Wrote a Python script to open/touch/close the `db` and the `temp` files disappeared.  

```
#load packages
import sqlite3
import glob
# List all db file names in the working dir
dbs = glob.glob('./03processed-data/apsimxFilesLayers/*.db')
# Loop 
for db in dbs:
    con = sqlite3.connect(db)
    mycur = con.cursor() 
    mycur.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;")
    (mycur.fetchall())
    mycur.close()
    con.close() 

```

**Comment by frank0434** [comment] 2020-10-27 02:18
Still have this issue when using it on HPC. 

![image](https://user-images.githubusercontent.com/30789416/97248817-721af700-1867-11eb-8b6b-2ccb86e971d3.png)
Re-run the apsimx files can reduce the number of files having this issue. but seems not an ideal solution. 

apsimx used was 2020.10.21.5755

**Comment by frank0434** [comment] 2020-10-27 02:27
Not sure if it relates to this issue as well. 
Recently, lots of `core.*` file were generated when running apsimx on the HPC. 

```
./core.45157
./core.204838
./core.230286
./core.169411
./core.14780
./core.287949
./core.85906
./core.79138
./core.296192
./core.88455
```
 `$file core.39006`
```
core.39006: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/usr/bin/mono 
usr/local/lib/apsim/2020.10.21.5755/Bin/Models.exe /workspace/cf', real uid: 1428, effective uid: 1428, real gid: 1428,
effective gid: 1428, execfn: '/usr/bin/mono', platform: 'x86_64'
```

**Comment by hol430** [comment] 2020-10-27 03:59
No idea where those core.* files are coming from. Could they be an artifact of the hpc?

The .db-wal and .db-shm files are still being cleaned up for me. It's hard to say why they're not being cleaned up for you, other than that the db connection is not being closed correctly. Are you sure apsim is not running when you copy the files off the hpc? (`pgrep -fa Models`)? Did the simulations run without error? How are you running the simulations? Which version of mono are you using?

**Comment by zur003** [comment] 2020-10-27 09:33
Is there a chance that some of the runs are "crashing"? A .core file is usually a dump of memory state at the time of program failure. Any crashes would also not close the database properly, and leave the .db-wal and .db-shm files behind.

**Comment by frank0434** [comment] 2020-10-29 20:00
Thanks, Drew. 

I asked our HPC guy. 
```
```

> No idea where those core.* files are coming from. Could they be an artifact of the hpc?

> The .db-wal and .db-shm files are still being cleaned up for me. It's hard to say why they're not being cleaned up for you, other than that the db connection is not being closed correctly. Are you sure apsim is not running when you copy the files off the hpc? (`pgrep -fa Models`)? Did the simulations run without error? How are you running the simulations? Which version of mono are you using?

**Comment by frank0434** [comment] 2020-10-29 20:09
Thanks, Drew. 

I asked our HPC guy. Below is his reply.
```
Usually created when a job fails for some reason. 
The cause can vary, but is usually an unhandled exception in the code of the application. 
In rare occasions it can be due to a kernel or hardware fault.
```

> No idea where those core.* files are coming from. Could they be an artifact of the hpc?

I didn't do any file management until all simulations finished. 

simulations were not free from errors - there were 15K simulations, some of them always have minor errors. 

We use apsimx as a singularity container on the HPC 
[Here](https://github.com/powerPlant/apsimx-srf/blob/master/Singularity.2020.10.21.5755) is the receipt to build the container. 

Not sure how the mono was installed. so not sure which version it is. 
wondering if the apsimx.deb already includes the mono it requires since the container should have all dependencies installed?

> The .db-wal and .db-shm files are still being cleaned up for me. It's hard to say why they're not being cleaned up for you, other than that the db connection is not being closed correctly. Are you sure apsim is not running when you copy the files off the hpc? (`pgrep -fa Models`)? Did the simulations run without error? How are you running the simulations? Which version of mono are you using?

**Comment by frank0434** [comment] 2020-10-29 20:13
Thanks, @zur003 

Probably yes. 
I need to try to reproduce this to have better understand the cause. this happened randomly and most of the time simulations finished clean if I re-run them. maybe some I/O issues between our HPC and storage disks? 

> Is there a chance that some of the runs are "crashing"? A .core file is usually a dump of memory state at the time of program failure. Any crashes would also not close the database properly, and leave the .db-wal and .db-shm files behind.

**Comment by frank0434** [comment] 2020-12-02 00:52
Hi team, after a few trial and errors. 
one of the reasons I think these temporary db files are caused by not enough disk space in `/home` directory. 
This might be specific to the PFR HPC system since we have limited space for each staff's `/home` and the job schedular we use at the moment (openlava). the job schedular will need a subdirectory `.lsbatch` at `/home` to generate all the command it gonna execute with some log files. This process eats up space super fast when there are more than a few thousand jobs.  
The apsim-NG singularity container will be terminated and left the simulation incomplete. 

The workaround our experts offered was to create a symlink directory to re-direct this `.lsbatch` directory to a place where has no space limitation. 

Hope this will be useful to someone may experience similar issue.
