### ISSUE TITLE
"Report Table Already Exists" Error

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#1690] opened 2017-05-29 01:51 UTC
When instances of report have different contents the simulations fail with an error about report table already existing.
Can be avoided by renaming reports of different structures and deleting the entire DB file.
See prototypes Nutrient model test set

**Comment by hol430** [comment] 2019-01-11 06:02
Closing this, as I'm unable to reproduce it. If someone notices this bug feel free to reopen.

**Closed by hol430** 2019-01-11 06:02 UTC
Labels: bug, interface/infrastructure
