### ISSUE TITLE
The GUI is somewhat unstable and crashes

### ISSUE THREAD

**Issue by hol353** [APSIMInitiative/ApsimX#5590] opened 2020-08-27 00:07 UTC
This is hard to reproduce reliably. It seems to happen after much clicking on nodes in the tree, copying and pasting within and between manager scripts and other components. In the screenshot below I copied a large chunk of c# from a manager script and renamed a node in the tree and hit ctrl V to paste the c# code. Not a valid thing to do but I was trying to get it to crash. The APSIM status message I think was from a previous attemp to paste something invalid on a node in the tree.

![image](https://user-images.githubusercontent.com/1943827/91368575-d3652080-e84c-11ea-93e8-5f7ad7112f38.png)

**Comment by MarkLieffering** [comment] 2020-09-02 00:10
If is of any help in diagnosing, when I start without debugging in VS after a crash (like just now) I invariably get a slightly different GUI - note how the bottom bar is white (usually all black) and the "stop" button has a red X (usually doesn't):

![image](https://user-images.githubusercontent.com/32279744/91917712-d1033a80-ed14-11ea-8b64-090e33d79a67.png)

when i close this and then start again without debugging in VS all is back to normal

**Comment by hol430** [comment] 2020-09-03 05:22
Yeah I've never managed to figure out why that's happening. It sometimes happens to me even when running with the debugger attached. Restarting apsim will usually fix the problem, although sometimes I need to restart it a few times. Does it happen for you every time you run without the debugger?

**Comment by MarkLieffering** [comment] 2020-09-03 19:54
You mean the strange GUI? - no not all the time but a lot of the time. The crashes usually happen when renaming nodes - will say "not responding at the top left (by "Custom build") and then woosh - all gone

**Comment by lie112** [comment] 2020-09-14 07:00
A user reported that she can reliably cause a crash (no error, closes APSIM) when using ctrl+v to paste copied nodes, whereas if she uses right click/paste from the popup menu it works. I haven't been able to repeat the problem and she's away for a week. This may be why people don't recognise what causes the problem as they automatically use ctrl+c and ctrl+v. The keystrokes work in reports etc, but this issue is with copying and pasting models in the simulation tree structure.

**Comment by hol430** [comment] 2020-09-14 22:21
There was an older issue where pasting some random text (not json/xml) into the tree would cause a crash, but that was a while ago. From what I understand of the recent crashes that have been reported, it seems to be related to renaming nodes, or pasting stuff onto them as you said, although I haven't managed to reproduce it consistently either. Let me know if this turns out to be a consistent repro of the bug.

**Comment by hol430** [comment] 2020-11-02 22:35
@hol353 @MarkLieffering - are you guys still seeing these crashes? I made a change about 2 months ago (#5660) which may have affected this, but it's hard to tell when the crashes don't happen reliably (for me, anyway).

**Comment by MarkLieffering** [comment] 2020-11-02 22:52
@hol430 - not as often as before - fingers crossed

**Comment by pre078** [comment] 2020-11-03 00:05
There seems to be a change - I'm not crashing as much but still using ctrl+c and ctrl+v in several places.

**Comment by pre078** [comment] 2020-11-10 22:55
CLEM (APSIMx) crashed 3 times yesterday - seems to be after highlighting text then pressing the Delete Key instead of the Backspace.  Can't get it to repeat after going back into APSIMs -seems to happen after doing several Cut & Pastes - happens in the Graph Filter, Model Rename, Custom Query (changing SQL txt)

**Comment by pre078** [comment] 2020-11-16 02:46
CLEM (APSIMx) just crashed again for me - after running simulation - clicked in the "summaryfile" display area - right-click "Select all" - Ctrl-C then crashed.  It worked when I tried to repeat the Copy with and without out running simulation -  for both Cntl-C and mouse right-click Copy

**Comment by sno036** [comment] 2021-01-28 01:30
It is not "somewhat" unstable. I've had five crashes in the last 2.5 hours. Coping the name of a component, changing the name of a component, ....

**Comment by lie112** [comment] 2021-01-28 01:52
I have also had some issues lately working with managing the UI simulation tree, but not sure how to repeat the problems. I am not sure how much can be inferred from the error dumps so maybe we provide them, but often it is a lethal error and APSIM is no more! 
Should we periodically dump the command history to a temp file and use that to see what the last things we were doing when the problems occurred, or doesn't that include the user action information relevant?
It is usually not the act of clicking, but after renaming, or a copy and paste a section of tree so suspect in the code behind.
Will keep up the detective work.

**Comment by hol430** [comment] 2021-01-28 02:09
As far as logs go - if apsim crashes, I'd be interested to see any Gtk-CRITICAL messages generated by ApsimNG.exe. I think they show up in the output window if you're running from visual studio(?).

**Comment by lie112** [comment] 2021-01-28 02:34
I noticed some the other day and was going to check if they were CLEM related and something I needed to fix. I think my GTK# is a bit sloppy. I'll keep an eye out.

**Comment by zur003** [comment] 2021-01-28 02:38
I see quite a few Gtk-CRITICAL messages, and the occasional GLib-CRITICAL. A brief non-crashing run had instances of:

gtk_widget_render_icon: assertion 'size > GTK_ICON_SIZE_INVALID || size == -1' failed
gtk_text_buffer_apply_tag: assertion 'tag->table == buffer->tag_table' failed
Source ID 7675 was not found when attempting to remove it

I don't think the icon size thing is particularly serious, but the others may be.

**Comment by hol430** [comment] 2021-01-28 05:33
Yeah, I suspect the icon size problem may not be related to the crash. It seems to be related to clicking through the simulations tree quickly when moving to/from a node with a gridview. I think the source ID problem has been fixed in a [more recent](https://gitlab.gnome.org/GNOME/gtk/-/commit/491d79d54083044a5de3bfa2d7afe9cced3974f0) version of gtk. The gtk_text_buffer_apply_tag output is interesting, I haven't seen that one and it's also not in the output I received from Val earlier. Are you running the latest version? I recall seeing these a few weeks/months ago but thought I had fixed them.

For posterity I'm including a list of distinct warnings I received from Val as well as a backtrace from a crash I managed to trap last year.

<details>

```
(ApsimNG:12720): GLib-CRITICAL **: Source ID 94122 was not found when attempting to remove it
(ApsimNG:12720): Gtk-CRITICAL **: gtk_tree_view_column_set_fixed_width: assertion 'fixed_width > 0' failed
(ApsimNG:12720): Gtk-CRITICAL **: gtk_widget_can_activate_accel: assertion 'GTK_IS_WIDGET (widget)' failed
(ApsimNG:12720): Gtk-CRITICAL **: gtk_widget_render_icon: assertion 'size > GTK_ICON_SIZE_INVALID || size == -1' failed
(ApsimNG:12720): Gtk-WARNING **: Can't set a parent on a toplevel widget
(ApsimNG:12720): Gtk-WARNING **: ../../gtk+-2.24.31/gtk/gtkliststore.c:612: Unable to convert from gchararray to gboolean
(ApsimNG:12720): Gtk-WARNING **: ../../gtk+-2.24.31/gtk/gtkliststore.c:612: Unable to convert from gchararray to GdkPixbuf
```

```
Thread 1 "mono" received signal SIGSEGV, Segmentation fault.
0x00007f847be04c5b in gtk_widget_can_activate_accel () from /usr/lib/libgtk-x11-2.0.so.0
(gdb) info stack
#0  0x00007f847be04c5b in gtk_widget_can_activate_accel () at /usr/lib/libgtk-x11-2.0.so.0
#1  0x00007f847bceae9c in  () at /usr/lib/libgtk-x11-2.0.so.0
#2  0x00007f848001ff85 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#3  0x00007f84800480b0 in  () at /usr/lib/libgobject-2.0.so.0
#4  0x00007f848003ba4b in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#5  0x00007f848003c980 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#6  0x00007f847be04c88 in gtk_widget_can_activate_accel () at /usr/lib/libgtk-x11-2.0.so.0
#7  0x00007f847bcf80ec in  () at /usr/lib/libgtk-x11-2.0.so.0
#8  0x00007f847bceae9c in  () at /usr/lib/libgtk-x11-2.0.so.0
#9  0x00007f8480020052 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007f84800480b0 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007f848003ba4b in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007f848003c980 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#13 0x00007f847be04c88 in gtk_widget_can_activate_accel () at /usr/lib/libgtk-x11-2.0.so.0
#14 0x00007f847be04ce6 in  () at /usr/lib/libgtk-x11-2.0.so.0
#15 0x00007f8480020052 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#16 0x00007f8480048685 in  () at /usr/lib/libgobject-2.0.so.0
#17 0x00007f848003ba4b in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#18 0x00007f848003c980 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#19 0x00007f847bc21d80 in gtk_accel_group_activate () at /usr/lib/libgtk-x11-2.0.so.0
#20 0x00007f847bc2328d in gtk_accel_groups_activate () at /usr/lib/libgtk-x11-2.0.so.0
#21 0x00007f847be1d436 in gtk_window_activate_key () at /usr/lib/libgtk-x11-2.0.so.0
#22 0x00007f847be1d492 in  () at /usr/lib/libgtk-x11-2.0.so.0
#23 0x00007f847bcea03c in  () at /usr/lib/libgtk-x11-2.0.so.0
#24 0x00007f8480020052 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#25 0x00007f84800480b0 in  () at /usr/lib/libgobject-2.0.so.0
#26 0x00007f848003ba4b in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#27 0x00007f848003c980 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#28 0x00007f847be066f8 in  () at /usr/lib/libgtk-x11-2.0.so.0
#29 0x00007f847bce880e in gtk_propagate_event () at /usr/lib/libgtk-x11-2.0.so.0
#30 0x00007f847bce8b3b in gtk_main_do_event () at /usr/lib/libgtk-x11-2.0.so.0
#31 0x00007f84802b85be in  () at /usr/lib/libgdk-x11-2.0.so.0
#32 0x00007f847b7fe43c in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#33 0x00007f847b84c1d9 in  () at /usr/lib/libglib-2.0.so.0
#34 0x00007f847b7fcc03 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#35 0x00007f847bce7b7e in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
#36 0x0000000041f56090 in  ()
#37 0x0000000000000000 in  ()
(gdb) info frame
Stack level 0, frame at 0x7ffdc03109a0:
 rip = 0x7f847be04c5b in gtk_widget_can_activate_accel; saved rip = 0x7f847bceae9c
 called by frame at 0x7ffdc03109d0
 Arglist at 0x7ffdc0310968, args: 
 Locals at 0x7ffdc0310968, Previous frame's sp is 0x7ffdc03109a0
 Saved registers:
  rbp at 0x7ffdc0310988, r12 at 0x7ffdc0310990, rip at 0x7ffdc0310998
(gdb) info args
No symbol table info available.
(gdb) info locals
No symbol table info available.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x55aefca8c7ed - mono : 
	0x55aefca8cb99 - mono : 
	0x55aefca37492 - mono : 
	0x55aefca85e99 - mono : 
	0x7f847be04c5b - /usr/lib/libgtk-x11-2.0.so.0 : gtk_widget_can_activate_accel
	0x7f847bceae9c - /usr/lib/libgtk-x11-2.0.so.0 : 
	0x7f848001ff85 - /usr/lib/libgobject-2.0.so.0 : g_closure_invoke
	0x7f84800480b0 - /usr/lib/libgobject-2.0.so.0 : 
	0x7f848003ba4b - /usr/lib/libgobject-2.0.so.0 : g_signal_emit_valist
	0x7f848003c980 - /usr/lib/libgobject-2.0.so.0 : g_signal_emit
	0x7f847be04c88 - /usr/lib/libgtk-x11-2.0.so.0 : gtk_widget_can_activate_accel
	0x7f847bcf80ec - /usr/lib/libgtk-x11-2.0.so.0 : 
	0x7f847bceae9c - /usr/lib/libgtk-x11-2.0.so.0 : 
	0x7f8480020052 - /usr/lib/libgobject-2.0.so.0 : g_closure_invoke
	0x7f84800480b0 - /usr/lib/libgobject-2.0.so.0 : 
	0x7f848003ba4b - /usr/lib/libgobject-2.0.so.0 : g_signal_emit_valist
	0x7f848003c980 - /usr/lib/libgobject-2.0.so.0 : g_signal_emit
	0x7f847be04c88 - /usr/lib/libgtk-x11-2.0.so.0 : gtk_widget_can_activate_accel
	0x7f847be04ce6 - /usr/lib/libgtk-x11-2.0.so.0 : 
	0x7f8480020052 - /usr/lib/libgobject-2.0.so.0 : g_closure_invoke
	0x7f8480048685 - /usr/lib/libgobject-2.0.so.0 : 
	0x7f848003ba4b - /usr/lib/libgobject-2.0.so.0 : g_signal_emit_valist
	0x7f848003c980 - /usr/lib/libgobject-2.0.so.0 : g_signal_emit
	0x7f847bc21d80 - /usr/lib/libgtk-x11-2.0.so.0 : gtk_accel_group_activate
	0x7f847bc2328d - /usr/lib/libgtk-x11-2.0.so.0 : gtk_accel_groups_activate
	0x7f847be1d436 - /usr/lib/libgtk-x11-2.0.so.0 : gtk_window_activate_key
	0x7f847be1d492 - /usr/lib/libgtk-x11-2.0.so.0 : 
	0x7f847bcea03c - /usr/lib/libgtk-x11-2.0.so.0 : 
	0x7f8480020052 - /usr/lib/libgobject-2.0.so.0 : g_closure_invoke
	0x7f84800480b0 - /usr/lib/libgobject-2.0.so.0 : 
	0x7f848003ba4b - /usr/lib/libgobject-2.0.so.0 : g_signal_emit_valist
	0x7f848003c980 - /usr/lib/libgobject-2.0.so.0 : g_signal_emit
	0x7f847be066f8 - /usr/lib/libgtk-x11-2.0.so.0 : 
	0x7f847bce880e - /usr/lib/libgtk-x11-2.0.so.0 : gtk_propagate_event
	0x7f847bce8b3b - /usr/lib/libgtk-x11-2.0.so.0 : gtk_main_do_event
	0x7f84802b85be - /usr/lib/libgdk-x11-2.0.so.0 : 
	0x7f847b7fe43c - /usr/lib/libglib-2.0.so.0 : g_main_context_dispatch
	0x7f847b84c1d9 - /usr/lib/libglib-2.0.so.0 : 
	0x7f847b7fcc03 - /usr/lib/libglib-2.0.so.0 : g_main_loop_run
	0x7f847bce7b7e - /usr/lib/libgtk-x11-2.0.so.0 : gtk_main
	0x41f56090 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7f84011fa640 from 0x7f8484754740
Pkilling 0x7f8484307640 from 0x7f8484754740
Pkilling 0x7f8401bff640 from 0x7f8484754740
Entering thread summarizer pause from 0x7f8484754740
Finished thread summarizer pause from 0x7f8484754740.
Failed to create breadcrumb file (null)/crash_hash_0xef853543

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
/tmp/mono-gdb-commands.233203:1: Error in sourced command file:
warning: process 233203 is already traced by process 233215
ptrace: Operation not permitted.

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7f847be04c5b):0x7f847be04c4b  a1 f2 ff ff 48 89 c6 48 8b 45 00 48 85 c0 74 05  ....H..H.E.H..t.
0x7f847be04c5b  48 39 30 74 0d 48 89 ef ff 15 af 70 1f 00 85 c0  H90t.H.....p....
0x7f847be04c6b  74 3b 31 c0 8b 35 1f aa 1f 00 4c 8d 44 24 04 44  t;1..5....L.D$.D
0x7f847be04c7b  89 e1 31 d2 48 89 ef ff 15 b0 5d 1f 00 8b 44 24  ..1.H.....]...D$

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at Gtk.Application:gtk_main <0x0008f>
	  at Gtk.Application:Run <0x00023>
	  at UserInterface.UserInterface:Main <0x0017f>
	  at <Module>:runtime_invoke_int_object <0x00091>
=================================================================
Aborted (core dumped)
```

</details>

**Comment by sno036** [comment] 2021-03-22 03:24
Still getting crashes on copying or pasting information. Can this be bumped up the list for attention please!

**Comment by her123** [comment] 2021-03-22 03:29
I'll second that. Frequent crashes after copying or pasting. Usually when I was editing factor values.

**Comment by zur003** [comment] 2021-03-22 04:05
I haven't been able to produce crashes, but I would note that copy-and-paste allows stuff to be pasted in inappropriate places. For example, I can paste a Fertiliser model as a child of a Report Model, which makes no sense. We should find a way to enforce the ValidParent attributes when pasting a model.

**Comment by hol430** [comment] 2021-03-22 04:18
Were you copying text into the factor, or copying factors into the simulations tree? Also do you have the beta property presenter turned on (it's off by default)?

**Comment by her123** [comment] 2021-03-22 05:42
I haven't changed any settings. Usually when copying text from a factor value (Ctrl-C) then click on something else - crash. It often takes a number of other changes before this can crash it.

**Comment by sno036** [comment] 2021-03-22 05:46
It happens when pasting all sorts of stuff - layered data from one component to another; text for renaming a component (F2 then Crtl+v); component from place A to place B (using control c v); test in a manager component; ....

**Comment by MarkLieffering** [comment] 2021-03-22 18:40
Just an insomnial thought from last night. Are the crashes only happening when people are using the LAG (latest and greatest) version (i.e. running through VS) or are they also happening when using the latest released version? I haven't used a released version for ages so can't contribute a data point.

**Comment by hol430** [comment] 2022-01-11 01:46
Is this still happening in gtk3 builds? (ie any versions from the last 3 months)

**Comment by sno036** [comment] 2022-01-11 19:00
Happy NY!

I think it vastly improved in the last months of 2021 (I even got through a while day without a crash!).

**Comment by peter-devoil** [comment] 2022-01-11 23:00
Ditto. MTBF is well past 10s of minutes.

**Comment by hol353** [comment] 2022-01-31 00:11
Ditto. I don't think I've seen a hard crash with the .net core version.

**Comment by hol430** [comment] 2022-01-31 00:36
I'm going to tentatively close this...feel free to re-open if need be.

**Closed by hol430** 2022-01-31 00:36 UTC
Labels: bug, interface/infrastructure
