### ISSUE TITLE
Thicknesses of soil layers are set at 999999 when converting Classic files

### ISSUE THREAD

**Issue by BrianCollinss** [APSIMInitiative/ApsimX#6243] opened 2021-03-14 01:52 UTC
![image](https://user-images.githubusercontent.com/39573622/111054852-abbd6900-84bb-11eb-9ae9-19fba979fe6f.png)

**Comment by hol430** [comment] 2021-03-15 01:33
Having trouble reproducing...can you upload your .apsim file?

**Comment by BrianCollinss** [comment] 2021-03-15 01:35
[OZCultivar.zip](https://github.com/APSIMInitiative/ApsimX/files/6138242/OZCultivar.zip)

**Comment by hol430** [comment] 2021-03-25 04:45
Could you upload your file from old apsim (ie with .apsim extension)? This archive only seems to have the .apsimx file.

**Comment by BrianCollinss** [comment] 2021-03-25 04:46
[Uploading OZCultivar.zip…]()

**Comment by BrianCollinss** [comment] 2021-03-25 04:46
[OZCultivar.zip](https://github.com/APSIMInitiative/ApsimX/files/6202105/OZCultivar.zip)

**Comment by hol430** [comment] 2021-03-29 02:20
I think it's being imported correctly, the problem that I see is that the .apsim file has 99999 for the thicknesses.

**Comment by hol430** [comment] 2021-06-16 05:22
I'm going to close this as not a bug. It's the file coming from old apsim that's the problem, not the importer itself.

**Closed by hol430** 2021-06-16 05:22 UTC
Labels: bug, interface/infrastructure
