### ISSUE TITLE
Problems with graphs after recent changes

### ISSUE THREAD

**Issue by BenAbabaei** [APSIMInitiative/ApsimX#3762] opened 2019-04-18 00:25 UTC
- When I copy the graph into Paint, the background is black.
![image](https://user-images.githubusercontent.com/39573622/56328880-4d4eb980-61c4-11e9-81c2-af137c387df1.png)

- Regression equation and statistics are not show,
![image](https://user-images.githubusercontent.com/39573622/56328865-47f16f00-61c4-11e9-8179-17cfbbf9fee2.png)

- The way the legend items are sorted still doesn't make sense. It seems it still depends on the order of the simulations.
![image](https://user-images.githubusercontent.com/39573622/56328920-8e46ce00-61c4-11e9-9972-7411cacaade1.png)

**Comment by hol430** [comment] 2019-04-18 01:33
1. Graph export to clipboard black background
This is fixed by #3763

2. Graphs not visible in folder
I believe the folder should only display graphs which are direct children of the folder. It will not show graphs which are children of an experiment inside the folder. Do you have any graphs which are direct children of the folder? If yes, could you upload your.apsimx and .met file

3. Regression stats not showing
This might be fixed by #3763

4. Order of items in legend
Duplicate of #3579

**Comment by BenAbabaei** [comment] 2019-04-18 01:36
Thanks Drew. Just reporting the problems. Regarding the second point, it used to show all the graphs. If you decided to change it, it is OK. Just to make sure the new setting was intentional.

**Comment by hol430** [comment] 2019-04-18 02:08
Regarding point 2 - no, this behaviour has not been deliberately changed. Are you sure it used to show all graphs? Looking at the code, it seems like folders have only ever displayed graphs for direct children, ever since the initial version of ApsimX. Any chance you can upload your .apsimx and .met files? I'm interested to see what setup you have if this was previously showing all of your graphs.

**Comment by BenAbabaei** [comment] 2019-04-18 02:14
In this file, **SE Queensland** folder used to show all the children graphs.

[2019.03.01.zip](https://github.com/APSIMInitiative/ApsimX/files/3092199/2019.03.01.zip)

**Comment by hol430** [comment] 2019-04-18 02:40
Weird - I can't see how the SE Queensland folder would have ever shown graphs, unless you removed some graphs which were direct children. How recently was this working for you? I've tested with a version from early April and it didn't show the graphs.

**Comment by hol430** [comment] 2019-04-18 02:42
Also, if you pull latest changes, are some of these problems fixed?

**Comment by BenAbabaei** [comment] 2019-04-18 02:56
Well, background is copied successfully. But regression formula and statistics are not shown. 
![image](https://user-images.githubusercontent.com/39573622/56333895-5c8c3200-61d9-11e9-84b1-1afbed64ea98.png)

When I tick "Display regression line and equation for each series", I get this:

![image](https://user-images.githubusercontent.com/39573622/56333888-54cc8d80-61d9-11e9-9772-cf2809f8ba9a.png)

**Comment by sme016** [comment] 2019-04-28 22:54
We still no stats shown - please reinstate.

Thanks,
Philip

**Closed** 2019-04-29 04:37 UTC
Labels: bug, interface/infrastructure
