### ISSUE TITLE
Clean code in Phenology.OnHarvesting

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#5491] opened 2020-08-04 10:40 UTC
Phenology.cs has the following text to deal with simplefruittree models (#3801)  It may be that rewinding of phenology as per grape or perrenial pastures could be used to have an interative or cycling phenology. 

        /// <summary>Called when crop is being harvested.</summary>
        [EventSubscribe("Harvesting")]
        private void OnHarvesting(object sender, EventArgs e)
        {
            //Jump phenology to the end
             if(this.Parent.Name != "SimpleFruitTree") //Unless you are a perennial fruit tree.  There must be a better way of doing this
                SetToStage((double)(phases.Count));
        }

**Comment by hut104** [comment] 2020-08-04 10:48
this is captured by #5490

**Comment by hol430** [comment] 2020-08-05 05:34
Duplicate of #5490

**Closed by hol430** 2020-08-05 05:34 UTC
