### ISSUE TITLE
No text wrapping in documentation

### ISSUE THREAD

**Issue by hut104** [APSIMInitiative/ApsimX#4689] opened 2020-02-07 05:01 UTC
A user has raised issues with reading much of our documentation.  We create tables of information using reflection and custom attributes.  However, when these are put into tables, the description attributes cannot fit on a single line and so text is truncated at the end of the single line, rather than allowing multiple lines and text wrapping.  Much of the information cannot be read.

For examples, see:
https://apsimdev.apsim.info/ApsimX/Releases/2020.02.05.4679/SoilWater.description.pdf https://apsimnextgeneration.netlify.com/modeldocumentation/

**Comment by hol430** [comment] 2020-02-07 05:05
Sounds like this is a duplicate of #4685. I will see what I can do to make the text wrap.

**Closed** 2020-02-18 03:30 UTC
Labels: documentation, refactor
